### ISSUE TITLE
Profile files can be read by anyone

### ISSUE THREAD

**Issue by Dist0rt3d** [graysky2/profile-sync-daemon#100]
I use psd to sync my firefox profile with overlayfs and i have noticed the profile directory in /tmp is readable by everyone, is there a good reason for this? This looks like a security issue.

**Comment by graysky2** [comment]
The simplest thing I do is to read the permissions on the sync target and have psd honor them, ie if you make ~/.mozilla/firefox/xxx.default 700 then psd will honor that.  The alternative is to simply make anything 700 by default.  The former gives more control to the user so I am thinking that might be best.

**Comment by graysky2** [comment]
Version 5.62 has a more complete implementation of this.  Thank you for for raising this issue.
https://github.com/graysky2/profile-sync-daemon/compare/v5.61...v5.62
