### ISSUE TITLE
Feature Request: Provide a command to clean all or some of the crash recovery snapshots.

### ISSUE THREAD

**Issue by Firef0x** [graysky2/profile-sync-daemon#102]
Hello, @graysky2 !

Appreciate your great work! :rose: 

Several days ago, I was suffered from frequently crashes of Firefox. After updating to Firefox 33.x, my computer hangs almost every 20 minutes, and I have to debug the browser over and over again. And I found that my `/home` partition is  out of disk space. OMG, I've never notice that there are several crash recovery snapshots taking up over 2 gigabyte disk space and make my `/home` partition out of disk space.

I've read the [Profile-sync-daemon - ArchWiki](https://wiki.archlinux.org/index.php/Profile-sync-daemon#My_system_crashed_and_didn.27t_sync_back._What_do_I_do.3F) and know that these crash recovery snapshots could be safely deleted. Since I have about 10 directories sync'ed( both profile-sync-daemon and anything-sync-daemon), there are over 50 crash recovery snapshots generated and I have to delete them one by one.

After that, I have rebuilt my Firefox profiles and it doesn't hang as often as before, but still hangs sometimes. I am too lazy to delete the crash recovery snapshots one by one after every crash, and hope that there would be a simpler way to do so.

 As [crashrecovery folders keep accumulating · Issue #75](https://github.com/graysky2/profile-sync-daemon/issues/75) mentioned, you don't want to have auto deleting and prefer leaving it to users to delete the snapshots as needed. And you have rejected [add crash recovery dirs handler by Nefelim4ag · Pull Request #79](https://github.com/graysky2/profile-sync-daemon/pull/79) for the same reason. I think adding a command to remove all or some crash recovery snapshots could leave the decision to users and simplify the cleaning process. It's a less radical and more compromised proposal. The advanced users could safely remove some snapshots easily after restored, and the basic users could just make it routine.

Do you agree with me? And is it worth a shot?

Hope for your reply! :heart_eyes: 

Yours sincerely! :bow:

**Comment by graysky2** [comment]
I think running a command to clean them is a good idea since it just automates a manual `rm -rf foo`.  I guess the command would apply to all managed profiles.  Let me think about how to to go about implementing it.  PRs are welcome and I will take another look at https://github.com/graysky2/profile-sync-daemon/pull/79

**Comment by lloydhazlett** [comment]
+1 for this idea, and can I also suggest an option to disable the creation of crash recovery directories entirely? In my case I have my home directory regularly backed up and I'm logged in to browser sync services, so a corrupted profile is easy to restore or recreate without the *-backup-crashrecovery directories. I'd rather it just remove the symlink and rename the *-backup so it can proceed as normal without the copy in the first place.

**Comment by graysky2** [comment]
Suppose I can do that as well.

**Comment by graysky2** [comment]
OK guys - Can you both please try the current code in my unstable branch?  I have implemented both features.

**Comment by gituser6** [comment]
This new feature gets me rock-hard.
+1 :star: for you, graysky!

**Comment by graysky2** [comment]
>This new feature gets me rock-hard.

Interesting comment. I suggest you seek the attention of a physiological professional or start your own fetish website for others with your unique turn-on :wink:

**Comment by gituser6** [comment]
Maybe I will! Can you make me a PKGBUILD for the git version? I don't want to do it outside of pacman.

**Comment by graysky2** [comment]
I had one in the AUR but decided to delete it a while back.  Maybe it's worth reupping.  Give me a few and look for it in there.

**Comment by gituser6** [comment]
It works for me and the git package works for me too.

**Comment by graysky2** [comment]
@Firef0x
@lloydhazlett

We good to merge into master?

**Comment by lloydhazlett** [comment]
Have only found the one issue in my testing, thanks for implementing.

**Comment by Firef0x** [comment]
Hello, @graysky2 !

Sorry for my late reply! I've tried my best to make a kernel panic while browsing Web pages, and finally I got my computer hangs. :smiley: After a restart, I found all my browsing status was kept completely. Then I tried executing the command `psd c`, and all the crash recovery snapshots were cleaned. Everything just worked good.

So, I think there is no regression or bug with the new feature added, and maybe we could merge it into `master` branch and release it. What's more, I hope this feature could be sync'ed to `anything-sync-daemon`.

Yours sincerely! :bow:

**Comment by graysky2** [comment]
Thanks guys.  Yes, I do plan to sync up with asd as well.

**Comment by Firef0x** [comment]
Thank you very much for implementing in `anything-sync-daemon` as well! :rose:

**Comment by graysky2** [comment]
yw
