### ISSUE TITLE
Feature request: qutebrowser

### ISSUE THREAD

**Issue by thiagowfx** [graysky2/profile-sync-daemon#105]
Upstream: https://github.com/The-Compiler/qutebrowser

I am not sure if the profile path is

    $HOME/.local/share/qutebrowser

or

    $HOME/.config/qutebrowser

But I believe that it is the first one, since the second directory only contains user configurations.

```
thiago@archpad ~ % ls -al .local/share/qutebrowser 
total 1036
drwx------  3 thiago thiago      95 Jan 26 11:17 ./
drwxr-xr-x 42 thiago users     4096 Jan 26 02:24 ../
-rw-r--r--  1 thiago thiago 1031962 Jan  5 01:29 blocked-hosts
-rw-------  1 thiago thiago    1328 Jan 26 11:17 cmd-history
-rw-------  1 thiago thiago   10805 Jan 26 11:17 cookies
drwxr-xr-x  2 thiago thiago    4096 Jan 26 11:13 local-storage/
-rw-------  1 thiago thiago     141 Jan 26 11:17 state
thiago@archpad ~ % ls -al .config/qutebrowser 
total 48
drwx------  2 thiago thiago    65 Jan 26 11:20 ./
drwx------ 69 thiago users   4096 Jan 26 03:23 ../
-rw-------  1 thiago thiago  5905 Jan 26 11:17 keys.conf
-rw-------  1 thiago thiago     0 Jan 26 11:17 quickmarks
-rw-------  1 thiago thiago 30460 Jan 26 11:17 qutebrowser.conf
```

**Comment by thiagowfx** [comment]
After reading #86, I'd sau `$HOME/.local/share/qutebrowser` is the desired directory.

**Comment by graysky2** [comment]
I don't see that either directory stores anything beyond a few text files.  As with https://github.com/graysky2/profile-sync-daemon/issues/86 if there isn't anything significant, there is no real point in syncing.

**Comment by thiagowfx** [comment]
I'm not sure yet -- it looks like the .local directory is used for caching purposes. I'm using qutebrowser as a secondary browser, so I don't have much cache in there for now.

```
thiago@archpad ~ % tree .local/share/qutebrowser 
.local/share/qutebrowser
├── blocked-hosts
├── cmd-history
├── cookies
├── local-storage
│   ├── https_en.wikibooks.org_0.localstorage
│   ├── https_en.wikipedia.org_0.localstorage
│   ├── https_github.com_0.localstorage
│   ├── https_twitter.com_0.localstorage
│   ├── https_www.facebook.com_0.localstorage
│   └── https_www.youtube.com_0.localstorage
└── state

1 directory, 17 files
thiago@archpad ~ % du .local/share/qutebrowser
1.5M	.local/share/qutebrowser/local-storage
2.5M	.local/share/qutebrowser
```

(Of course, I omitted some websites for the sake of brevity and my privacy)

Is there any website I could access from qutebrowser that creates a lot of files in the cache? I guess that if the cache increases to, say, 10-20MB+, then we could confirm it is a cache (not just config files).

**Comment by graysky2** [comment]
Not sure... I think it's also about how the browser caches stuff.  I just installed it for testing purposes.  Please use it and let me know if it's worth adding.

**Comment by thiagowfx** [comment]
I used it during the last hours, but the size remains the same (1.5M and 2.5M). I'm beginning to think that the `.local/share/qutebrowser` folder is not a cache either. Well, I guess this issue can be closed then. Thanks for your replies!
