### ISSUE TITLE
Opera Legacy (in Arch)

### ISSUE THREAD

**Issue by Grarap** [graysky2/profile-sync-daemon#111]
Is there any chance opera-legacy from the AUR can be supported? It doesn't seem to be covered by activating PSD for Opera.

**Comment by graysky2** [comment]
What is the profile path for opera legacy?  Also, what is the path to the binary (post the output of `ps aux | grep opera` while you're running opera legacy).

**Comment by Grarap** [comment]
That's ~/.opera-legacy (well, that's where it puts everything and that's what used to be .opera, so it should be the profile path, right?) and /usr/lib/opera-legacy/opera-legacy.

**Comment by graysky2** [comment]
Wish granted, long live jambi: https://github.com/graysky2/profile-sync-daemon/compare/v5.69...v5.70

**Comment by Grarap** [comment]
Wow, that was quick, thanks a lot.
The config dir seems to be wrong though, it's not at ~/.config/opera-legacy, but at ~/.opera-legacy (or am I misunderstanding something?).

**Comment by graysky2** [comment]
Typo on my part.  Will correct later today.

On Tuesday, March 10, 2015, Grarap <notifications@github.com> wrote:

> Wow, that was quick, thanks a lot.
> The config dir seems to be wrong though, it's not at
> ~/.config/opera-legacy, but at ~/.opera-legacy (or am I misunderstanding
> something?).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/profile-sync-daemon/issues/111#issuecomment-78177630>
> .
>


-- 
Sent from Gmail Mobile

**Comment by graysky2** [comment]
Please try 5.71 and report back.

https://github.com/graysky2/profile-sync-daemon/compare/v5.70...v5.71

**Comment by Grarap** [comment]
Yes, it seems to work (I didn't even try your first commit since I was curious in the code changes and noticed that it was not going to work).
The link is there.
Thanks!
