### ISSUE TITLE
google-chrome-unstable cache growing to outrageous sizes

### ISSUE THREAD

**Issue by seanlaguna** [graysky2/profile-sync-daemon#112]
I checked the size of my google-chrome-unstable cache the other day (using du from the terminal) and it was over 5 gigabytes! This is in direct violation to the fact that my cache should be size-limited to ~272 megabytes (for me) according to the values present in chrome://net-internals/#httpCache.

I am using overlayfs and am using /tmp as my dir (yes it has permissions of 777) because I am experiencing a previously-mentioned issue where there are some systemd conflicts (systemd-hostnamed and systemd-localed to be precise) when I use /dev/shm as is the default. This is running Debian Ubuntu Jessie/Unstable.

I cleared my cache and restarted psd.conf and opened chrome anew. I'll report back and see if it passes the limit again, but for now, I can say this definitely happened. Maybe overlayfs is causing some problems?

**Comment by graysky2** [comment]
I doubt overlay is doing anything to cause that.  I use chromium not chrome so I can't comment, but I'm thinking your issue of large cache is independent of psd.  Using /tmp or /dev/shm is fine for psd.
