### ISSUE TITLE
google-chrome-stable not managed

### ISSUE THREAD

**Issue by millerthegorilla** [graysky2/profile-sync-daemon#114]
midori and firefox are managed ok, but google-chrome-stable is not showing when psd p is run.  ps -A lists google-chrome-stable as 'chrome' - perhaps this is the reason?

**Comment by millerthegorilla** [comment]
This is on xubuntu vivid vervet beta 1 (upgraded) which I will soon replace with the stable release of vivid.  Many thanks.

**Comment by graysky2** [comment]
Post the output of:
`sed -e 's/#.*$//' -e '/^$/d' /etc/psd.conf`

**Comment by millerthegorilla** [comment]
thanks

USERS="super"
BROWSERS="midori firefox google-chrome-stable"
VOLATILE="/run/shm"
DAEMON_FILE="/var/run/psd"
USE_OVERLAYFS="yes"



On Mon, Apr 13, 2015 at 8:26 PM, graysky <notifications@github.com> wrote:

> Post the output of:
> sed -e 's/#.*$//' -e '/^$/d' /etc/psd.conf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/profile-sync-daemon/issues/114#issuecomment-92469657>
> .
>



-- 
James Stewart Miller Bsc(hons) Psych.

**Comment by millerthegorilla** [comment]
I tried changing the Browsers line to "midori firefox chrome" but psd complains that there is no such browser.

**Comment by graysky2** [comment]
Looks ok... next question is where is the profile dir for that browser on your system?

**Comment by graysky2** [comment]
Ping millerthegorilla
