### ISSUE TITLE
Mozilla Thunderbird as a "browser"

### ISSUE THREAD

**Issue by waltkelly** [graysky2/profile-sync-daemon#115]
I have cloned the repository and modified the psd script to support Mozilla Thunderbird (email client) profiles. As Thunderbird profiles are organized very similarly to Firefox profiles, I think this fits the _profile-sync-daemon_ schema better than it would fit the _anything-sync-daemon_. 

On Linux Mint 17.1 `psd p` produces:

    Profile-sync-daemon v5.99 on Ubuntu 14.04.2 LTS

     Daemon pid file is present.
     Resync cronjob is present.
     Overlayfs v22 is currently active.

    Psd will manage the following per /var/run/psd.conf settings:

     browser/psname:  firefox/firefox
     owner/group id:  parz/1000
     sync target:     /home/parz/.mozilla/firefox/tm5tbzxr.default
     tmpfs dir:       /run/shm/parz-firefox-tm5tbzxr.default
     profile size:    140M
     overlayfs size:  60M
     recovery dirs:   none

     browser/psname:  thunderbird/thunderbird
     owner/group id:  parz/1000
     sync target:     /home/parz/.thunderbird/ioj5obig.default
     tmpfs dir:       /run/shm/parz-thunderbird-ioj5obig.default
     profile size:    625M
     overlayfs size:  176M
     recovery dirs:   none

If this is generally useful and not harmful, I'd like to contribute the change,  if someone would assist me in merging this back to github - something I have no experience in.

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/issues/14
