### ISSUE TITLE
Losing both firefox and chromium profiles - multiple users

### ISSUE THREAD

**Issue by RobDean69** [graysky2/profile-sync-daemon#118]
I have been using PSD for some time now on a computer running Kubuntu with two user accounts without a problem however last week I upgraded to Kubuntu 15.04. Now, seemingly when one user logs out then another logs in (only one users profiles are synced with PSD) and the computer is rebooted the browser profile is gone and a clean one is used (bookmarks gone, extensions gone etc). This happens with both firefox and chromium. How do I troubleshoot this?

**Comment by RobDean69** [comment]
Output of psd p (only syncing chromium at the moment).

rob-carly@rob-carly-P5KR:~$ psd p
Profile-sync-daemon v5.73 on Ubuntu 15.04

 Daemon pid file is present.
 Resync cronjob is present.
 Overlayfs v23 is currently active.

Psd will manage the following per /var/run/psd.conf settings:

 browser/psname:  chromium/chromium
 owner/group id:  rob-carly/1000
 sync target:     /home/rob-carly/.config/chromium
 tmpfs dir:       /run/shm/rob-carly-chromium
 profile size:    59M
 overlayfs size:  59M
 recovery dirs:   2 <- delete with the c option
  dir path/size:  /home/rob-carly/.config/chromium-backup-crashrecovery-20150512_100349 (127M)
  dir path/size:  /home/rob-carly/.config/chromium-backup-crashrecovery-20150517_185225 (149M)

**Comment by graysky2** [comment]
Haven't seen this behavior on my system with multiple users.  If the problem started with the update to 15.04, we should start looking there.  Does 15.04 user systemd natively?

**Comment by thuandt** [comment]
I'm lost my firefox profile when I upgraded to Ubuntu 15.04.
Ubuntu 15.04 use systemd and start psd with systemd-sysv-generator.
I think @graysky2 should rebuild psd (using systemd) for ubuntu 15.04 (PPA). I compile psd from source and it work fine.

**Comment by RobDean69** [comment]
Yes, as far as I can tell my system is using systemd (not sure about natively. If I run the command "cat /proc/1/comm" it returns "systemd").

**Comment by graysky2** [comment]
OK guys, please see my readme for psd.  I cannot continue providing packages for distros that I do not run.  For Ubuntu with systemd, please build the util yourself using `make install-systemd-all` per the INSTALL doc and it should be fine.  I do plan to support systemd distros so please stop psd, build it yourself with systemd support, and see if that solves your issues.  Open a new ticket if not.
