### ISSUE TITLE
The psd.service takes long to load at boot.

### ISSUE THREAD

**Issue by leander091** [graysky2/profile-sync-daemon#121]
Hi,

Thank you for this program its very useful. 

Could you help me with the following issue? The service takes about 12 seconds to load on my laptop is it possible to reduce that time?
I'm using archlinux with a ssd and my firefox profile is 450M. 

```
systemd-analyze blame
  12.403s psd.service
```
```

systemd-analyze critical-chain
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.

graphical.target @13.482s
└─multi-user.target @13.482s
  └─psd.service @1.078s +12.403s
    └─basic.target @1.038s
      └─sockets.target @1.037s
        └─dbus.socket @1.037s
          └─sysinit.target @1.036s
```
```
Profile-sync-daemon v5.73 on Arch Linux

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs technology is currently inactive.

Psd will manage the following per /run/psd.conf settings:

 browser/psname:  firefox/firefox
 owner/group id:  leander091/1000
 sync target:     /home/leander091/.mozilla/firefox/3tpc46z8.default
 tmpfs dir:       /tmp/leander091-firefox-3tpc46z8.default
 profile size:    450M
 recovery dirs:   3 <- delete with the c option

```

**Comment by graysky2** [comment]
Nothing is wrong with psd... 450 M is a considerable profile so it's just a load of data to send around.  You can do several things:

1) Use overlayfs mode which will be considerably faster.
2) Reduce the size of your profile (see man page if you're writing cache to the profile) and use [https://aur.archlinux.org/packages/profile-cleaner](profile-cleaner) to gain some space.
3) Update your hardware to a fast SSD.

**Comment by leander091** [comment]
Thank you for the support. After enabling overlayfs the time  is reduced to  297ms
