### ISSUE TITLE
Sync-resync not working by default on Ubuntu 14.04

### ISSUE THREAD

**Issue by bokiscout** [graysky2/profile-sync-daemon#122]
HI, 
I'm using Ubuntu 14.04 (kernel 3.13) with KDE.

PSD = profile-sync-daemoon

1. What is the issue?
Each boot new crash directory is being made no matter which browser I'm syncing.
PSD is not active on boot (even dough I manually run "sudo service psd start" to gain autostart functionality).

2. When have I installed PSD?
About weak ago.

3. How do I install PSD?
It is compiled from source code.

4. Were there any strange/unwanted behavior of PSD during installation?
No, there weren't any unwanted behavior.
PSD compiled successfully.
All Ubuntu specific and upstart specific scripts were executed during installation.

5. What was I suspecting to be the issue for behavior described in "1."?
No proper sync or resync being executed on boot and before shutdown/restart.

6. What I've done to prove what I was suspecting?
 deleted all recovery directories ("profile-sync-daemon clean").
Manually start PSD (by executing "/etc/init.d/psd start" in terminal).
Check status ("profile-sync-daemon parse")
Manually stop PSD (by executing "/etc/init.d/psd stop" in terminal).
Check status ("profile-sync-daemon parse")

 No recovery directories were created.

7. What I've done next to prove what I was suspecting?
I made bash script that executes "/etc/init.d/psd start" on boot
I made bash script that executes "/etc/init.d/psd stop" before shutdown and before restart.

Scripts were made using this (http://ccm.net/faq/3348-ubuntu-executing-a-script-at-startup-and-shutdown) tutorial.

No recovery directory were found anymore
PSD is running on boot.

Whole process was tested on Ubuntu 14.04 with Unity, Ubutnu 14.04 with KDE, Mint KDE and Xubuntu 14.04 each one with kernel 3.13. PSD is behaving as described in 1. and the solution is the one described in 7. in each case.

Maybe it is just me not compiling it right aka missing some step, maybe there is and issue with the script it self.

What I do to install it is running "sudo make install-upstart-all" and by reading the output I can realize that all provided Ubuntu specific scripts are executed and changes are visible there where should be made by manually checking every file created or used by PSD.

Thank you,
Borche Jankovski aka bokiscout.

**Comment by graysky2** [comment]
It seems like psd isn't being called by your init system which is upstart.  Did you enable psd in upstart?  Remove your custom bash scripts and use the init system.  Does it work for you?

```
update-rc.d -f psd remove >/dev/null 2>&1
update-rc.d psd defaults
```

**Comment by bokiscout** [comment]
Well this is the step that was missing.  Now psd is working fine without the scripts.

Thank you.

**Comment by graysky2** [comment]
You're welcome.  I updated the INSTALL document, manpage, and my README to make this more clear.
