### ISSUE TITLE
Installed the wrong way on linux mint 17.2 :(

### ISSUE THREAD

**Issue by reddot15** [graysky2/profile-sync-daemon#125]
installed package from
https://launchpad.net/~graysky/+archive/ubuntu/utils/+files/profile-sync-daemon_5.74-1_all.deb

running linux mint 17.2 mate, 

got some warning in the synaptic package manager, 
E: profile-sync-daemon: package profile-sync-daemon is not ready for configuration  cannot configure (current status `half-installed')

so i tried to remove profile-sync-daemon, and i cant. 

i get error
E: profile-sync-daemon: subprocess installed post-removal script returned error exit status 127

i read to late that i was suppose to build it ;(
how do i remove it?

**Comment by reddot15** [comment]
(synaptic:4165): GLib-CRITICAL **: g_child_watch_add_full: assertion 'pid > 0' failed
(Reading database ... 232667 files and directories currently installed.)
Removing profile-sync-daemon (5.74-1) ...
dpkg: error processing package profile-sync-daemon (--remove):
 subprocess installed post-removal script returned error exit status 127
Errors were encountered while processing:
 profile-sync-daemon
E: Sub-process /usr/bin/dpkg returned an error code (1)
A package failed to install.  Trying to recover:

**Comment by reddot15** [comment]
i couldnt wait any longer so i just reinstalled linux mint

**Comment by graysky2** [comment]
There is no need to reinstall your entire OS.  I am not familiar with dpkg or why your particular one gave a non-zero exit code.  In the future, you can simply remove the files owned by the package and call it good.

**Comment by reddot15** [comment]
i could not get it t remove or reinstall it was a mess, i looked up how to remove half install packages and nothing worked, also removing it using the deb file did not work it would close completely. i gave up and started over. thanks by the way for nice program

**Comment by graysky2** [comment]
YW
