### ISSUE TITLE
Interferences with Firefox addon installation and upgrade

### ISSUE THREAD

**Issue by neitsab** [graysky2/profile-sync-daemon#126]
Since a few Firefox releases (I'm currently using 39.0 and Profile-sync-daemon v5.73 on Arch Linux), I observe issues with addons installation/update.

Most frequent case is I'm trying to manually install/upgrade uBlock Origin from its [GitHub releases](https://github.com/gorhill/uBlock/releases), and after addon download and authorization a pop-up would appear at the far left of the address bar saying:

> uBlock could not be installed because Firefox could not modify the needed file.

No amount of browser restart would fix it, however I think restarting the whole system worked a few times.

Today I was having the same issue again, and also noticed an HTTPS Everywhere (automatic) update, with a line in the extension page saying the addon would be installed after Firefox restarts.

However, restarting the browser didn't result in the extension being upgraded: everything was exactly the same as before, with the extension still being in the `staged` folder of my profile directory.

This led me to suspect something with psd and the multiple folders in `/tmp` (I use overlayfs). Here is the ouptut of `profile-sync-daemon parse`:

```
Profile-sync-daemon v5.73 on Arch Linux

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /run/psd.conf settings:

 browser/psname:  firefox/firefox
 owner/group id:  neitsab/1000
 sync target:     /home/neitsab/.mozilla/firefox<redacted>.default
                   Permissions are 755 on this profile.
                   Recommend a setting of 700 for increased privacy!
 tmpfs dir:       /tmp/neitsab-firefox-<redacted>.default
 profile size:    143M
 overlayfs size:  86M
 recovery dirs:   none
```
Then I disabled the services (which crashed Firefox :-/ ), restarted the browser and proceeded to upgrade uBlock, without any issue. Also, HTTPS Everywhere was upgraded too.

Let me know if you need more info (if it may help, kernel is official `Linux 4.1.2-2-ARCH` from a few weeks ago).

Thanks

**Comment by graysky2** [comment]
No sure what the addons are doing.  If you stop psd, disable overlayfs and restart it, do the problems go away?

**Comment by graysky2** [comment]
Can you try that and update this request?

**Comment by lliseil** [comment]
Have had the issue that happened to neitsab when installing or updating FF addons while psd with overlayfs active on Arch. If it happens again I'll try your tip and hopefully report here.

**Comment by graysky2** [comment]
@neitsab - any report disabling overlayfs and getting the problem to appear?

**Comment by neitsab** [comment]
@graysky2 Sorry for the delay, I had muted all conversations by mistake and didn't see this one had so many replies :-o

I'm not in the capacity to test it anymore, but with the numerous updates to psd, kernel etc. it's likely a thing of the past. Feel free to close the issue, and I'll reopen/comment on it if I'm able to reproduce the bug.

**Comment by graysky2** [comment]
OK.

**Comment by lliseil** [comment]
Reoppening as I could test after it happened again.
Issue: Couldn't install an add-on
Action taken: 
- Set `XDG_RUNTIME_DIR=/run/user/1000/` && `DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"` as they were missing (related post on the forum https://bbs.archlinux.org/viewtopic.php?id=201543)
- Stopped psd, disabled overlayfs and restarted it: add-on installed right away.

**Comment by graysky2** [comment]
Version 6.14 should fix this.  Please try it and report back here if you would: https://github.com/graysky2/profile-sync-daemon/archive/v6.14.tar.gz

**Comment by lliseil** [comment]
Re-enabled ovarlayfs and it happened again; below is a more detailed output just in case:

* psd v6.12-2
* Overlay: 270 used on >378
* Log:

        1445968744448	addons.xpi	WARN	Failed to install /tmp/tmp-42w.xpi from https://addons.mozilla.org/firefox/downloads/file/238534/startupmaster-1.6-fx+tb.xpi?src=api: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < forEach()@self-hosted:210 < recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1538 < forEach()@self-hosted:210 < recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1538 < DirInstallLocation_getTrashDir()@resource://gre/modules/addons/XPIProvider.jsm:7535 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7557 < AI_startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6010 < next()@self-hosted:673 < TaskImpl_run()@resource://gre/modules/Task.jsm:330 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740 < <file:unknown>
        1445968744450	addons.xpi	WARN	removeActiveInstall: could not find active install for https://addons.mozilla.org/firefox/downloads/file/238534/startupmaster-1.6-fx+tb.xpi?src=api

psd p

    sync target:     /home/user/.mozilla/firefox/PROFILE
    tmpfs dir:       /run/user/1000//user-firefox-PROFILE
    profile size:    39M
    overlayfs size:  15M

Updating psd now thank you graysky.

**Comment by graysky2** [comment]
OK, please try 6.14 and report back.

**Comment by lliseil** [comment]
Profile-sync-daemon 6.14-1 on Arch
Yet I couldn't install an add-on on Firefofox 41, with ~300 MB free space in overlayfs.
Message's the same:

    <ADDON> could not be installed because Firefox could not modify the needed file.

* Restarting FF didn't help.
* Disabling overlayfs and restarting FF I could install the add-on.

Just in case thisz box shows:
    Failed to connect to bus: Aucun fichier ou dossier de ce type # that's when login in via ssh.

    $ echo $DBUS_SESSION_BUS_ADDRESS 
    unix:path=/run/user/1000//bus

**Comment by graysky2** [comment]
Which addon did you attempt to install?

**Comment by lliseil** [comment]
Right now, 'Cleanest addon manager' and 'Smart Referer'. Seems none will install when overlays ON; I'll try in a clean profile and come back. I'm sync'in bookmarks and history and it's really faster with PSD! Also thank you graysky for another quick reaction.

**Comment by graysky2** [comment]
I was able to install cleanest addon manager...?

**Comment by lliseil** [comment]
Aah that you could install that one is interesting. Situation is getting eeer better

Profile-sync-daemon 6.14-1 on Arch
Overlayfs has 24M taken on 378M

### On profile One (used)

*Cleanest Addon Manager* (No Restart) couldn't install, from both about:addons and from AMO

    1446238608248	addons.xpi	ERROR	Failed to remove empty directory /home/kozaki/.mozilla/firefox/8d5d8vlw.TESTin/extensions/trash: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_getTrashDir()@resource://gre/modules/addons/XPIProvider.jsm:7535 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7557 < AI_startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6010 < next()@self-hosted:673 < TaskImpl_run()@resource://gre/modules/Task.jsm:330 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740 < <file:unknown>
    1446238608250	addons.xpi	WARN	Failed to install /tmp/tmp-106.xpi from https://addons.mozilla.org/firefox/downloads/latest/358612/addon-358612-latest.xpi?src=ss: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_getTrashDir()@resource://gre/modules/addons/XPIProvider.jsm:7535 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7557 < AI_startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6010 < next()@self-hosted:673 < TaskImpl_run()@resource://gre/modules/Task.jsm:330 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740 < <file:unknown>
    1446238608251	addons.xpi	WARN	removeActiveInstall: could not find active install for https://addons.mozilla.org/firefox/downloads/latest/358612/addon-358612-latest.xpi?src=ss

### On New profile
Installed a number of addons without a glitch, then:

*Blackout* woudn't install 

    1446235811276	addons.xpi	ERROR	Failed to remove empty directory /home/kozaki/.mozilla/firefox/frktmf4x.allPlaces/extensions/trash: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7623 < XPI_processPendingFileChanges/<()@resource://gre/modules/addons/XPIProvider.jsm:2846 < forEach()@self-hosted:210 < XPI_processPendingFileChanges()@resource://gre/modules/addons/XPIProvider.jsm:2675 < XPI_checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3730 < XPI_startup()@resource://gre/modules/addons/XPIProvider.jsm:2305 < callProvider()@resource://gre/modules/AddonManager.jsm:221 < _startProvider()@resource://gre/modules/AddonManager.jsm:828 < AMI_startup()@resource://gre/modules/AddonManager.jsm:996 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2669 < AMC_observe()@resource://gre/components/addonManager.js:58 < <file:unknown>
    1446235811277	addons.xpi	WARN	Failed to remove trash directory when installing blackout-ext@skyweb.hu: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7623 < XPI_processPendingFileChanges/<()@resource://gre/modules/addons/XPIProvider.jsm:2846 < forEach()@self-hosted:210 < XPI_processPendingFileChanges()@resource://gre/modules/addons/XPIProvider.jsm:2675 < XPI_checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3730 < XPI_startup()@resource://gre/modules/addons/XPIProvider.jsm:2305 < callProvider()@resource://gre/modules/AddonManager.jsm:221 < _startProvider()@resource://gre/modules/AddonManager.jsm:828 < AMI_startup()@resource://gre/modules/AddonManager.jsm:996 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2669 < AMC_observe()@resource://gre/components/addonManager.js:58 < <file:unknown>

Then on further try, Blackout installed correctly !? As for Cleanest Addon Manager (No Restart):

    1446237221888	addons.xpi	ERROR	Failed to remove empty directory /home/kozaki/.mozilla/firefox/frktmf4x.allPlaces/extensions/trash: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_getTrashDir()@resource://gre/modules/addons/XPIProvider.jsm:7535 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7557 < AI_startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6010 < next()@self-hosted:673 < TaskImpl_run()@resource://gre/modules/Task.jsm:330 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740 < <file:unknown>
    1446237221890	addons.xpi	WARN	Failed to install /tmp/tmp-mei.xpi from https://addons.mozilla.org/firefox/downloads/latest/358612/addon-358612-latest.xpi?src=search: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.remove]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: recursiveRemove :: line 1541"  data: no] Stack trace: recursiveRemove()@resource://gre/modules/addons/XPIProvider.jsm:1541 < DirInstallLocation_getTrashDir()@resource://gre/modules/addons/XPIProvider.jsm:7535 < DirInstallLocation_installAddon()@resource://gre/modules/addons/XPIProvider.jsm:7557 < AI_startInstall/<()@resource://gre/modules/addons/XPIProvider.jsm:6010 < next()@self-hosted:673 < TaskImpl_run()@resource://gre/modules/Task.jsm:330 < Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922 < this.PromiseWalker.walkerLoop()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:801 < this.PromiseWalker.scheduleWalkerLoop/<()@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:740 < <file:unknown>
    1446237221891	addons.xpi	WARN	removeActiveInstall: could not find active install for https://addons.mozilla.org/firefox/downloads/latest/358612/addon-358612-latest.xpi?src=search

Also *Places Maintenance* did not seem to achieve anything
At this point I restarted.

*Places Maintenance* worked flawlessly
But *Cleanest Addon Manager* would not install, from both about:addons and from AMO. Log's the same as before restart.

*ExportHTMLFolder* couldn't install from about:addons, but did install from AMO...

Bizarre, bizarre, vous avez dit bizarre ?

**Comment by graysky2** [comment]
I cannot reproduce.  Here I have firefox synced using overlayfs and I installed cleanest addon manager as you did without a restart:
```
% firefox 

(process:9579): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
firefox  5.70s user 0.51s system 8% cpu 1:16.03 total
```

No errors.

**Comment by lliseil** [comment]
Hi, graysky that is strange:
even the add ons above that did act as standard when installing, ie didn't threw out any error message, weren't really installed.  "Restart to install <add on>" firefox prints out upon... restarting, until restarting with overlays disabled then they're installed for good. Both profiles.
Firefox stable, Arch up to date including psd and kernel ck, yeah standard too: ext4 for both / and /home `noatime error=remount-ro,discard` on LVM. I've disabled overlayfs for the momemt and will keep an eye on it, eg when updatin.

**Comment by graysky2** [comment]
OK.  Will close since I cannot repeat.
