### ISSUE TITLE
Option to Have Profiles Managed for All Users?

### ISSUE THREAD

**Issue by noctuid** [graysky2/profile-sync-daemon#127]
Would it be possible to add a a setting to manage any/all users' profiles without having to list the specific names in USERS (like all browsers is the default)? This would be a slight convenience since it could allow the same psd.conf to work across multiple computers regardless of the usernames. Not a huge deal, so if it you don't think it's a worthwhile to implement, then that's understandable.

**Comment by graysky2** [comment]
Strategically, I think doing that would be a poor choice.  A better option from my end would be not needing root access to run psd, but if I keep the ability to use overlayfs, I don't know how to accomplish that without users being having sudo access.  Let me think on the later.

**Comment by graysky2** [comment]
I have taken significant steps towards psd running in systemd's --user mode.  Check the unstable branch.

**Comment by noctuid** [comment]
Thank you; it's working well so far.
