### ISSUE TITLE
Per user psd.conf file location

### ISSUE THREAD

**Issue by StuntsPT** [graysky2/profile-sync-daemon#130]
It currently defaults to `$HOME/.psd/psd.conf`, but shouldn't it be located under `$HOME/.config/psd/psd.conf`?
If you think this makes sense, I would be happy to implement it. Hopefully it's not yet too late.

Thanks.

**Comment by RankoKohime** [comment]
I too would like to see the config file move to the XDG spec.  Too many programs create home folder clutter, and I'd like PSD not to be one of them.  :+1:

**Comment by jonpolak** [comment]
makes sense to me.

**Comment by graysky2** [comment]
I can move it...

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/compare/v6.02...v6.03

**Comment by RankoKohime** [comment]
Thank you very much for this, I can't tell you how much this helps my sanity.  :smiley:

**Comment by graysky2** [comment]
YW.  At least one of us can be sane :stuck_out_tongue_closed_eyes:

**Comment by StuntsPT** [comment]
Thank you! This is much appreciated!
