### ISSUE TITLE
Thunderbird/Icedove support

### ISSUE THREAD

**Issue by jcharaoui** [graysky2/profile-sync-daemon#14]
I haven't tested it yet, but the script should also work for the Thunderbird email client with minimal modification. The profiles work pretty much the same way.

**Comment by heniokalinowski** [comment]
Benefits are the same as for Firefox - faster and more responsive software. I agree with my predecessors, it would be great to add this feature (especially, that it would be Firefox feature adaptation). I have about 37 email accounts and profile weights several GBs and would really speed it up with 64 GB of RAM. There already exists a config file that allows disabling psd for Thunderbird, if anyone wouldn't want to use it.

I see only advantages and see no disadvantages of adding it.

There are numerous requests for adding it across nearly 10 years - please consider adding it.

anything-sync-daemon is not available in Debian repository (only in Arch), and even if, then it's still better to have a single daemon  and single config, than two.
