### ISSUE TITLE
Can't using psd with overlayfs in Ubuntu 15.04

### ISSUE THREAD

**Issue by thuandt** [graysky2/profile-sync-daemon#140]
I can't using overlayfs option with Ubuntu 15.04 with version 6.11. Version 5.74 work fine.

As a document, I added this line to `/etc/sudoers`

`mrtux ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper`

After that, I'm restart my laptop. But  it don't work. psd is always display that I need add above line to `/etc/sudoers`.

Can you help me solve this?

**Comment by thuandt** [comment]
I solved it.

Because we default user when installation in group `sudo`, so I must put this line to the end of `/etc/sudoers` to make it work.

`%sudo ALL=(ALL:ALL) ALL`

**Comment by graysky2** [comment]
Maybe I am not understanding... post for me /etc/sudoers without comments like this (you must run this as root):
```
sed -e '/^#/d' -e '/^$/d' /etc/sudoers
```

Now post for me the output of running `id` as your mrtux user.

**Comment by thuandt** [comment]
@graysky2 `NOPASSWD` line need at in the end of `/etc/sudoers` file

```
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
root  ALL=(ALL:ALL) ALL
%admin ALL=(ALL) ALL
%sudo   ALL=(ALL:ALL) ALL
mrtux ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper

```

**Comment by graysky2** [comment]
Your your, mrtux, is not in the sudo group so I don't see why you would need to add the line you mentioned.  The final line you entered should be sufficient.  Just for kicks, comment out the line you added starting with "%sudo" and leave in the mrtux line.  Now logout and log back in, enable overlayfs, and post the output of `psd p`

**Comment by thuandt** [comment]
I know what I'm doing :)
`mrtux` is my username, line with `%sudo` and `%admin` is already be there (I'm enable it)

Line I mention is `mrtux ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper`. Maybe we're have misunderstanding

**Comment by graysky2** [comment]
This version of psd will check to see if your user can execute /usr/bin/psd-overlayfs-helper via a sudo call without a password. If you do not specify the 'NOPASSWD' directive for your user, it will not operate.  In you case, only the 'mrtux ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper' line is required.  If you also want your user in a master group of %sudo for example that does not need the password, you will need both lines.

**Comment by thuandt** [comment]
I'm total agree :+1:
