### ISSUE TITLE
Add support of Jetbrain IDEs

### ISSUE THREAD

**Issue by zafarella** [graysky2/profile-sync-daemon#142]
Thank you for the daemon!
Would you consider adding support of Jetbrain IDE? It requires same concept - syncing the compiler output and logs/temp files of the ide.

Thanks

**Comment by Nefelim4ag** [comment]
I think, since recently psd have modular structure, you can write and use local modules modules for this 
Something like /usr/share/psd/browsers/JetBrain_IDE
And read source before it, of cource.

**Comment by graysky2** [comment]
psd is really intended for browsers... please use asd for this sort of work
