### ISSUE TITLE
[solved] overlay filled up

### ISSUE THREAD

**Issue by lliseil** [graysky2/profile-sync-daemon#143]
Profile-sync-daemon v6.11 on Arch Linux.
Reached overlayd max available size:

    tmpfs                 tmpfs     3,0G  149M  2,9G   5% /tmp
    tmpfs                 tmpfs     201M  201M     0 100% /run/user/1000
    overlaid              overlay   201M  201M     0 100% /run/user/1000/[firefox-profile-1]
    overlaid              overlay   201M  201M     0 100% /run/user/1000/[firefox-profile-2]
    overlaid              overlay   201M  201M     0 100% /run/user/1000/[palemoon-profile-1]

Happened after starting Firefox v41. Took much longer time than usual. Lookin in the related profile, saw Fx created a 197 MB places.sqlite.wal [1], letting ~no room for the rest. 

`psd -p` shows no information on the profiles. Neither does `systemctl --user status psd`. Enlarged tmpfs size to no effect on the user's tmpfs/overlay --found no information on how to act on the later atm.

EDIT: stopped psd, launched Fx which this time rebuilt places.sqlite-wal till the end (up to 500M!). After what places.sqlite was rebuilt with all the history lost :/
 
Beside reporting to yoru attention, I'd like if you can tell what possible action should be taken in such a case?

[1] http://forums.mozillazine.org/viewtopic.php?f=40&t=2333075

**Comment by graysky2** [comment]
The standard way of controlling the size of /run/user is the
RuntimeDirectorySize
directive

in logind.conf: http://www.freedesktop.org/software/systemd/man/logind.conf.html


10% of physical memory is the default but you can up it safely.
Remember that tmpfs only uses what is actually used.  The number you
specify here is just a max. allowed.



On Tuesday, September 29, 2015, Cyr La <notifications@github.com> wrote:

> Profile-sync-daemon v6.11 on Arch Linux.
> Reached overlayd max available size:
>
> tmpfs                 tmpfs     3,0G  149M  2,9G   5% /tmp
> tmpfs                 tmpfs     201M  201M     0 100% /run/user/1000
> overlaid              overlay   201M  201M     0 100% /run/user/1000/[firefox-profile-1]
> overlaid              overlay   201M  201M     0 100% /run/user/1000/[firefox-profile-2]
> overlaid              overlay   201M  201M     0 100% /run/user/1000/[palemoon-profile-1]
>
> Happened after starting Firefox v41. Took much longer time than usual.
> Lookin in the related profile, saw Fx created a 197 MB places.sqlite.wal
> [1], letting ~no room for the rest.
>
> psd -p shows no information on the profiles. Neither does systemctl
> --user status psd. Enlarged tmpfs size with no effect on the user's
> tmpfs/overlay --found no information on how to act on the later atm.
>
> Beside reporting to yoru attention, I'd if you can tell what possible
> action should be taken in such a case?
>
> [1] http://forums.mozillazine.org/viewtopic.php?f=40&t=2333075
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/profile-sync-daemon/issues/143>.
>


-- 
Sent from Gmail Mobile

**Comment by lliseil** [comment]
Got it graysky. Thanks!
Though I didn't find how to make it apply without rebooting. Restartiing systemd-logind after I closed users sessions didn't suffice; maybe auto-login is to be deactivated.

**Comment by graysky2** [comment]
You're welcome.  I will add this to the man page.

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/commit/97815a4d2df8f812c95d2425f20cfd980ec4dbcb
