### ISSUE TITLE
Feature request: Slimjet browser support

### ISSUE THREAD

**Issue by elundmark** [graysky2/profile-sync-daemon#144]
I'd love to see this browser added, http://www.slimjet.com/en/webhelp/index.htm
On my system it stores profiles in `~/.config/slimjet/` - seems simple enough.

**Comment by graysky2** [comment]
Can you copy the chromium profile to slimjet and test, then send a PR?
/usr/share/psd/browsers/

**Comment by graysky2** [comment]
@elundmark - Did that work for you?

**Comment by elundmark** [comment]
On 26/10/15 19:07, graysky wrote:
>
> @elundmark <https://github.com/elundmark> - Did that work for you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/graysky2/profile-sync-daemon/issues/144#issuecomment-151230266>.
>

Oh, so sorry I forgot I had this; I'll test it asap and post the 
results. I've even uninstalled psd (switched ttly to Slimjet) so I have 
to start over again.

// Erik

**Comment by graysky2** [comment]
If you are no longer interested, no need to try it out.

**Comment by MikeFlint** [comment]
Four years later, but I've just switched to using Slimjet, and followed your suggestion of cloning the chromium definition. This seems to be working - i.e. it shows in "psd p" and the profile sync is taking place if I look in syslog. I've not had a crash yet to verify recovery process.
