### ISSUE TITLE
Dont know how to install on linux mint 17.2 with upstart

### ISSUE THREAD

**Issue by reddot15** [graysky2/profile-sync-daemon#145]
pepe@D5758-PC ~/Desktop/profile-sync-daemon-master $ make
Setting version

pepe@D5758-PC ~/Desktop/profile-sync-daemon-master $ sudo make install
Installing main script...
install -p -d "/usr/bin"
install -p -m755 common/profile-sync-daemon "/usr/bin/profile-sync-daemon"
install -p -m755 common/psd-overlay-helper "/usr/bin/psd-overlay-helper"
ln -s profile-sync-daemon "/usr/bin/psd"
install -p -d "/usr/share/zsh/site-functions"
install -p -m644 common/zsh-completion "//usr/share/zsh/site-functions/_psd"
install -p -d "/usr/share/psd/browsers"
install -p -m644 common/psd.conf "/usr/share/psd/psd.conf"
cp common/browsers/* "/usr/share/psd/browsers"
Installing manpage...
install -p -d "/usr/share/man/man1"
install -p -m644 doc/psd.1 "/usr/share/man/man1/psd.1"
gzip -9 "/usr/share/man/man1/psd.1"
ln -s psd.1.gz "/usr/share/man/man1/profile-sync-daemon.1.gz"
Installing systemd files...
install -p -d "/usr/lib/systemd/user"
install -p -m644 init/psd.service "/usr/lib/systemd/user/psd.service"
install -p -m644 init/psd-resync.service "/usr/lib/systemd/user/psd-resync.service"
install -p -m644 init/psd-resync.timer "/usr/lib/systemd/user/psd-resync.timer"

i dont see anything in the documentation how to install on ubuntu 12.04 LTS / Linux Mint
what commands do i enter or what do i edit to make install on upstart.

thanks btw

**Comment by graysky2** [comment]
It is documented in several files including the README and manpage:
https://github.com/graysky2/profile-sync-daemon/blob/master/README.md#note-for-version-6
https://github.com/graysky2/profile-sync-daemon/blob/master/doc/psd.1#L95

You can use the last in the 5.x series for upstrart support, https://github.com/graysky2/profile-sync-daemon/archive/v5.75.tar.gz

**Comment by reddot15** [comment]
thanks, i was trying to install the latest. i did not know i could select a certain version. level:noob :+1:
