### ISSUE TITLE
PepperFlash not working at all in Google Chrome when using PSD with overlayfs

### ISSUE THREAD

**Issue by FadeMind** [graysky2/profile-sync-daemon#148]
Issue
==

PepperFlash plugin in Chrome not working at all when PSD with overlaysys is active.
Screenshoot with my native polish language (`LANG=C` not working for chrome):
![img](http://i.imgur.com/Vw3B0xN.png)

**Nie można załadować wtyczki** MEAN **Cannot load a plugin**

Starting PSD services
Profile-sync-daemon v6.12 on Arch Linux`

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.`

Psd will manage the following per /home/tomasz/.config/psd/psd.conf:

 browser/psname:  google-chrome/chrome
 owner/group id:  tomasz/100
 sync target:     /home/tomasz/.config/google-chrome
 tmpfs dir:       /run/user/1000/tomasz-google-chrome
 profile size:    414M
 overlayfs size:  0
 recovery dirs:   none`

**Comment by FadeMind** [comment]
When overlayfs is disabled PepperFlash plugin in Google Chrome working like a charm:
![s](http://i.imgur.com/rzxrPtc.png)

**Comment by graysky2** [comment]
Do you believe there is something wrong with the way I am calling the overlayfs mount?  I will need to play with this on my own machine.

**Comment by graysky2** [comment]
I cannot reproduce... browsing to www.adobe.com/software/flash/about/ with psd enabled shows the animation.  Stopping psd and returning there also shows the animation.

**Comment by FadeMind** [comment]
@graysky2 this issue is in **Google Chrome** when overlayfs is enabled in psd settings. 
When overlayfs is disabled all is fine.

**Comment by graysky2** [comment]
My bad.... didn't read carefully and I don't use the google product, just chromium.  Let me try it.

**Comment by graysky2** [comment]
.. cannot reproduce with google chrome from AUR.
Without psd enabled: I see the animation and am told I am running version 19.0.0.207 installed.
Start psd with overlayfs: same result :/

```
Profile-sync-daemon v6.12 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/facade/.config/psd/psd.conf:

 browser/psname:  google-chrome/chrome
 owner/group id:  facade/100
 sync target:     /home/facade/.config/google-chrome
 tmpfs dir:       /run/user/1000/facade-google-chrome
 profile size:    8.1M
 overlayfs size:  2.6M
 recovery dirs:   none
```

**Comment by FadeMind** [comment]
I made test with new one profile - clean profile. Aaaand overlayfs not affect flash plugin.
**Just new profile setup I have to using.**

**Comment by FadeMind** [comment]
Naah... After setup ublock origin, https-everywhere, tampermonkey issue return. 
OK then, I will using PSD without overlayfs.

**Comment by graysky2** [comment]
So it's multifactoral....

**Comment by graysky2** [comment]
@FadeMind - Do you think this is related to https://github.com/graysky2/anything-sync-daemon/issues/23 ?  I am still trying to wrap my mind around it.  ASD and PSD use the overfay mount in the same way when they resync.

**Comment by FadeMind** [comment]
@graysky2 I watching asd and psd github, and I know about it issue. ;)
Yep IMO is the same issue.

Without overlayfs Flash in GC is available and works
With overlayfs Flash in GC in NOT available.

It is looks like overlayfs missing some files (or ignore them - flash plugin PPAPI).

**Comment by graysky2** [comment]
@Nefelim4ag - Do you have any thoughts?  I am not seeing a great advantage to using the overlayfs mount aside from a faster startup. At somepoint (first resync) the lowerdir will need to be written in its entirety so the resync can write back to it.  Perhaps I am missing something?

**Comment by Nefelim4ag** [comment]
@graysky2,
if i understand topic correctly,
we get a troubles, if we sync data, to the lowerdir dir
And for this, we have two solutions:
1. Full resync from  lowerdir to the tmpfs
2. Have a separated dir, to sync, from ram, and after shutdown, just sync it to lowerdir

if i remember correctly, i write overlay patch for: decrease memory footprint and for faster startup, because ssd users, use psd, only for decrease wearout of memory cells

Then, if choise first option - it's better end easy, to just remove overlayfs support, because it's look like simple tmpfs sync

if choise second, we need a memory/io tradeoff like:
a) create a copy of lowerdir, and sync to them, and while stopping just sync it to lowerdir and remove it
b) Same, but use a fs clone, which AFAIK supported by XFS & BTRFS
c) Have a 2 profile, one is a general and second for the sync, and not remove it, after psd shutdown, just sync to lowerdir
Then we use more disk space, but get the ~ same startup time
And for systems, who uses fs clone -> just add button, to cleanup separeted profile, for saving disk space

**Comment by graysky2** [comment]
I think 2a is the most general, yes?

2b needs a special file system as you showed.

How does 2c differ from 2a?  PSD will need a copy of the profile to be the
"readonly" lower directory if we use overlayfs at all, yes?

Thank you!

**Comment by Nefelim4ag** [comment]
@graysky2,
2с - don't delete copy of profile if user stop psd
2a - delete copy of profile if user stop psd

Yes, you are understanding me right

glad to help you

**Comment by graysky2** [comment]
Any chance of a PR from you :)

On Sunday, October 25, 2015, Timofey <notifications@github.com> wrote:

> @graysky2 <https://github.com/graysky2>,
> 2с - don't delete copy of profile if user stop psd
> 2a - delete copy of profile if user stop psd
>
> Yes, you are understanding me right
>
> glad to help you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graysky2/profile-sync-daemon/issues/148#issuecomment-150898056>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Nefelim4ag** [comment]
https://github.com/graysky2/profile-sync-daemon/pull/149

**Comment by FadeMind** [comment]
@graysky2 @Nefelim4ag 

I installed now lastest git snapshot of profile-sync-daemon 

BTW. @graysky2 please update aur code: 
`source=("git://github.com/graysky2/profile-sync-daemon#branch=$_branch")`
branch=unstable doesn't exist.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=profile-sync-daemon-git

I have: **Profile-sync-daemon v6.12.r0.g97815a4.unstable on Arch Linux**
and overlayfs working like a charm. Adobe Flash in Chrome is available. 

[tomasz@arch ~]$ psd p
Profile-sync-daemon v6.12.r0.g97815a4.unstable on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/tomasz/.config/psd/psd.conf:

 browser/psname:  google-chrome/chrome
 owner/group id:  tomasz/100
 sync target:     /home/tomasz/.config/google-chrome
 tmpfs dir:       /run/user/1000/tomasz-google-chrome
 profile size:    266M
 overlayfs size:  49M
 recovery dirs:   none

Regards

**Comment by FadeMind** [comment]
@graysky2 
I return to using psd and on stable and later git release - flash plugin not working again in Chrome.
Can't load plugin:
![zaznaczenie_005](https://cloud.githubusercontent.com/assets/9846948/12006090/1bc96de4-abc7-11e5-8ac6-68bb54334305.png)

[tomasz@arch ~]$ psd p
Profile-sync-daemon vr617.0a961ce on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/tomasz/.config/psd/.psd.conf:

 browser/psname:  google-chrome/chrome
 owner/group id:  tomasz/100
 sync target:     /home/tomasz/.config/google-chrome
 tmpfs dir:       /run/user/1000/tomasz-google-chrome
 profile size:    274M
 overlayfs size:  37M
 recovery dirs:   none

[tomasz@arch ~]$ la .config/|grep chrome
drwx------ 10 tomasz users 4,0K 26.12.2015 11:47 google-chrome-back-ovfs/
drwx------ 10 tomasz users 4,0K 26.12.2015 11:47 google-chrome-backup/
lrwxrwxrwx  1 tomasz users   35 26.12.2015 11:47 google-chrome -> /run/user/1000/tomasz-google-chrome/

**Comment by graysky2** [comment]
I installer google-chrome from the AUR and am running psd with overlayfs enabled.

```
grep "^[^#;]" .config/psd/psd.conf
USE_OVERLAYFS="yes"
BROWSERS="google-chrome"
USE_BACKUPS="no"
```

![screenshot_2015-12-26_11-13-06](https://cloud.githubusercontent.com/assets/534822/12007083/dae58c7c-abc1-11e5-8225-865a8a2189b8.jpg)

**Comment by FadeMind** [comment]
@graysky2  My fail. During using new clean chrome profile I don't have this issue. 
Regards.
