### ISSUE TITLE
psd-resync.service missing

### ISSUE THREAD

**Issue by scwalla** [graysky2/profile-sync-daemon#154]
When psd is run for the first time it prints out the following suggested command:
  systemctl --user [option] psd psd-resync

Trying to start psd-resync fails with error "No such file or directory"

**Comment by graysky2** [comment]
How did you install psd and on which distro are you running it

Run the following as your user (not root):
```
systemctl --user daemon-reload
systemctl --user start psd
```

**Comment by scwalla** [comment]
I am running on Arch linux.  The results from psd p are posted below.  Same both before and after running the commands you suggested.  It looks like all is running correctly doesn't it?  Isn't this just a documentation problem?  The first run of psd says to start psd-resync.

Profile-sync-daemon v6.19 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs technology is currently inactive.

Psd will manage the following per /home/steve/.config/psd/psd.conf:

 browser/psname:  firefox/firefox
 owner/group id:  steve/1000
 sync target:     /home/steve/.mozilla/firefox/ii4ha3vr.default
 tmpfs dir:       /run/user/1000/steve-firefox-ii4ha3vr.default
 profile size:    30M
 recovery dirs:   none

**Comment by graysky2** [comment]
I corrected the wording of that error (https://github.com/graysky2/profile-sync-daemon/commit/6cf5bda87beb1cd0e366dd7ddd886db46aa990b1) directing the user to simply start psd not both psd and psd-resync.  That was a remnant of an older version that should have been corrected before.  Looks like you're up and running.  Enjoy.  Reopen if problems.
