### ISSUE TITLE
Chrome can't load flash

### ISSUE THREAD

**Issue by eviansfulda** [graysky2/profile-sync-daemon#157]
On ubuntu 15.10 and on Arch Linux, Chrome browser can't load flash plugin if psd service started, even with fresh browser profile.

**Comment by graysky2** [comment]
I can't reproduce this... https://github.com/graysky2/profile-sync-daemon/issues/148

**Comment by eviansfulda** [comment]
Deleting /home/evians/.config/google-chrome/PepperFlash resolved issue.

Somehow wrong-permissions, i guess:

google-chrome-stable 
[29467:29467:0104/104123:ERROR:CONSOLE(65)] "Uncaught Error: Attempting to use a disconnected port object", source: extensions::messaging (65)
Fontconfig error: Cannot load default config file
[128:128:0104/104143:ERROR:ppapi_thread.cc(328)] Failed to load Pepper module from /home/evians/.config/google-chrome/PepperFlash/20.0.0.267/libpepflashplayer.so (error: /home/evians/.config/google-chrome/PepperFlash/20.0.0.267/libpepflashplayer.so: cannot open shared object file: Operation not permitted)

stat /home/evians/.config/google-chrome/PepperFlash/20.0.0.267/libpepflashplayer.so 
  File: ‘/home/evians/.config/google-chrome/PepperFlash/20.0.0.267/libpepflashplayer.so’
  Size: 17908672  	Blocks: 34984      IO Block: 4096   regular file
Device: 804h/2052d	Inode: 5636498     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/  evians)   Gid: (  100/   users)
Access: 2016-01-04 10:36:47.736663565 +0200
Modify: 2015-12-30 02:01:12.244833707 +0200
Change: 2015-12-30 02:01:12.244833707 +0200
 Birth: -

**Comment by graysky2** [comment]
Glad you figured it out.

**Comment by darkangel-ua** [comment]
I can confirm that deleting ~/.config/google-chrome/PepperFlash resolve issue. But if I stop/start psd problem start to happen again. I can't find any difference in permissions when psd running and when not.

**Comment by graysky2** [comment]
While I'm glad we are getting closer to the root cause, I don't see how the rsync operation is doing this...  psd is really nothing more than an glorified invocation of rsync.

@MagicFish1990 and @darkangel-ua - Are you both running Arch Linux?  What version of rsync is installed?  What version of google-chrome and of pepper-flash?

**Comment by darkangel-ua** [comment]
Kubuntu 15.10 x64
Google Chrome Version 47.0.2526.106 (64-bit)
rsync 3.1.1-3
PepperFlash 20.0.0.267 - google download it each time I delete folder

I will try to play more with this issue to understand what's happening.

**Comment by eviansfulda** [comment]
Like others here,to me problem is still persistent, i kinda gave up on it, wild guess, it's something how psd-overlay-helper is enabled with sudo rights in  /etc/sudoers, maybe different users have different group access rights that's interfering with psd-overlay-helper or something along these lines.

**Comment by graysky2** [comment]
I will try to reproduce again on my system. In the past, I could not.

**Comment by eviansfulda** [comment]
Yes, i'm using up tu date Arch, but as i mentioned in the beginning in Ubuntu 15.10 problem was the same. If i remember right, some time before there was no need for psd to edit sudoers in Arch, to enable overlayfs, maybe problem lies somehow with that method, but that's not explains same behavior on Ubuntu and with Ubuntu user permissions couldn't much differ from one installation to another.

**Comment by graysky2** [comment]
I am using an up-to-date Arch x86_64 system I just spunup into a clean partition and cannot reproduce this.  My user is in the wheel group and I have that set to work without passwords in /etc/sudoers... is this how you guys experiencing problems have your sudoers setup?
* google-chrome (47.0.2526.106-1)
* chromium-pepper-flash (1:20.0.0.228-1)
* rsync (3.1.2-1)

**Comment by graysky2** [comment]
Actually, I am finding that ~/.config/google-chrome/PepperFlash is empty ... can you suggest some websites I can browse to that will cause it to fill up?

**Comment by eviansfulda** [comment]
[addictinggames](http://www.addictinggames.com/car-games/crazycle-game.jsp); [cnn](http://edition.cnn.com/videos/politics/2016/01/05/obama-crying-gun-executive-action-sot.cnn); [bbc](http://www.bbc.com/news/world-latin-america-35269411)

**Comment by graysky2** [comment]
So I browsed to those sites with PSD disabled and I still have an empty ~/.config/google-chrome/PepperFlash

**Comment by eviansfulda** [comment]
For now issue is gone - again, even after reboot! All flash content is working - for now, this seems to bee some esoteric bug. For now i'm to having a hard time to fill my PepperFlash directory with anything. Hope to hear something from others who is affected.

**Comment by MagicFish1990** [comment]
No idea what happened, I removed PepperFlash 3 days ago, but it become empty forever.
Flash works correct.
I will continue to check this issue.

**Comment by MagicFish1990** [comment]
Seems Chrome will update Flash plugin into PepperFlash if it was not updated.
So it maybe happen at the next flash upgrade.

**Comment by graysky2** [comment]
I still cannot get this to reproduce even on a fresh install to a new partition.  Guess we'll leave this issue open and all keep an eye out for it again, but I do not use google-chrome nor do I use pepperflash with chromium so someone will have to describe reproducible conditions for me for testing.

**Comment by Unholy616** [comment]
For me this bug manifests like that: If overlayfs enabled, flash just does not work. Else everything is OK.

**Comment by graysky2** [comment]
> For me this bug manifests like that: If overlayfs enabled, flash just does not work. Else everything is OK.

Is ~/.config/google-chrome/PepperFlash empty or...??

**Comment by Unholy616** [comment]
Strange:
~/.config/google-chrome/PepperFlash contained some files ('latest-component-updated' in that folder and 'libpepflashplayer.so', 'manifest.so', 'manifest.json' in version subdir). These files were there both with overlayfs and without it. 

Tried emptying this folder: Now flash works with and without overlayfs. Seems that now it uses system installation of 'libpepflashplashplayer.so'.

So far can't reproduce eviansfulda reported repopulation of the folder.

**Comment by graysky2** [comment]
Yeah, I am also confused by this and cannot reproduce.

**Comment by MagicFish1990** [comment]
Hi, I found out the reason.
When using a outdated PPAPI Flash (20.0.0.267, and the newest is 20.0.0.286), Chrome will download Flash update automatically into ~/.config/google-chrome-unstable/PepperFlash, which actually is /run/user/1000/xxxxx-google-chrome-unstable/PepperFlash/.
But the overlay filesystem has a noexec flag, then it cannot be loaded.

Try this
sudo mount -o remount,exec /run/user/1000/YOUR-CHROME-OVERLAY

I do not know if this should be regarded as a security feature or a BUG.

Need to download a old version of Chrome to reproduce.

"""
Name:	Shockwave Flash
Description:	Shockwave Flash 20.0 r0
Version:	20.0.0.286
Location:	/run/user/1000/xxxxx-google-chrome-unstable/PepperFlash/20.0.0.286/libpepflashplayer.so
Type:	PPAPI (out-of-process)
"""

**Comment by graysky2** [comment]
@MagicFish1990 - Nice!  

> I do not know if this should be regarded as a security feature or a BUG.

A little of both I guess... I see that systemd does not use the `noexec` flag when it creates `/run/user/xxxx` so perhaps I could simply remove this flag from the overlayfs option since the non-overlay option does not have it.  I don't know if keeping it as-is offers increased security or just a sense of it :pensive:
