### ISSUE TITLE
Feature request: qutebrowser (2)

### ISSUE THREAD

**Issue by csantosb** [graysky2/profile-sync-daemon#160]
Following #105, I have noticed that qutebrowser is using `~/.cache/qutebrowser`as its default cache. After a few days using it, I get around ~ 50 MB of data.

**Comment by graysky2** [comment]
`man psd`

> *Note that some browsers such as Chrome/Chromium, Firefox (since v21), Midori, and Rekonq actually keeps their cache directories separately from their browser profile directory. It is not within the scope of profile-sync-daemon to modify this behavior; users wishing to relocate this directory, may refer to the following url for several work-arounds: https://wiki.archlinux.org/index.php/Chromium_Tips_and_Tweaks#Cache_in_tmpfs

**Comment by csantosb** [comment]
Yes, you're right, the `--cachedir` flag
