### ISSUE TITLE
Work better with invalid soft links in profile directory

### ISSUE THREAD

**Issue by KeithCu** [graysky2/profile-sync-daemon#163]
I installed the new version of PSD, and it took me a while to get it working because even after following the Arch wiki instructions it didn't create the /run/user directory), etc.

The problem was that in my Mozilla profile was a soft link to a tmp directory that didn't exist. (I believe it was created by a previous version of PSD.) It would be great to handle this invalid link, or to log an error message explaining to the user that something went wrong, and why. I believe there is an message being ignored by PSD somewhere.

If PSD cannot create the /run/user directory and therefore not be effective, it should make a prominent warning and give the user a hint on how to fix the problem.

**Comment by graysky2** [comment]
Good idea.

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/commit/0d39d36aa4448ac8d1b2cd318bb0023161abb1e2

Addresses the warning piece both in the script an man page.
