### ISSUE TITLE
Provide standard Checkinstall instructions

### ISSUE THREAD

**Issue by jonpolak** [graysky2/profile-sync-daemon#164]
I was building `psd`  from source for a while, and, recently went back to the repo (Debian Stretch). I found that using `make install` leaves files all over the place that would then cause subsequent installs to fail (files existed where none where expected). 

## Suggest
Use [Checkinstall](https://wiki.debian.org/CheckInstall). This creates a deb file from the source and allows your package manager to track all the files. If you provide the right info for maintainer - package name etc - then users can go back to the repo anytime as the package manager notifies you when the installed version is older than the one available in the repo. 

## Request
Provide a standard file _checkinstallrc_ in the repo which contains pkg/maintainer info

**Comment by graysky2** [comment]
Debian is not my primary distro and frankly, the package manager there is complicated relative to some.  I don't want to increase the overhead on my end to maintain for it due to a lack of time.  I don't understand how the leftover files you are describing are present on the live file system of a user who downloads the deb I provide... for me when I remove that package via apt-get, there are no files on the live file system.

**Comment by jonpolak** [comment]
the only time there are leftover files is if you install with `make install`  / if you install with `checkinstall` then that problem goes away. What I'm suggesting is an edit to the readme that says,

> If you plan on building from source and are using debian based distro (Mint, Ubuntu) then use CHECKINSTALL -D  instead of `make install`. This will generate a deb file which you can install with gdebi or dpkg and thus your package manager will continue to keep track of all the projects's files.

**Comment by graysky2** [comment]
> I found that using make install leaves files all over the place

Which files are leftover?

**Comment by jonpolak** [comment]
Oh man. That was a while ago. It was the symlinks I think.

in general installing with make install always leaves stuff. That's why
they invented CHECKINSTALL. Makes a nice package first that apt/yum can
cleanly keep track.

**Comment by graysky2** [comment]
Not sure which symlinks you're talking about... the 3 that are made on `make install` are removed on `make uninstall` and for those using packages I would think that every good manager (apt, pacman, etc.) would grab them.  Thank you for the report, but I don't think I'll be taking any action at this time.
