### ISSUE TITLE
PSD starts new instance of firefox every hour

### ISSUE THREAD

**Issue by LordTaifleh** [graysky2/profile-sync-daemon#166]
also running psd p in terminal does not show details but also just launches firefox

**Comment by graysky2** [comment]
Is this still affecting you? Please post the output of:
```
psd p
cat ~/.config/psd/psd.conf
```

**Comment by graysky2** [comment]
Any word?

**Comment by LordTaifleh** [comment]
I'm sorry, this was no bug, it was my own stupidity (as it is so often)
I took out the # in  front of "firefox" in the list of browsers instead of setting BROWSERS="firefox"
My guess is, reading the config file every hour (when syncing) just issued a launch command for firefox.  It works fine now :D

**Comment by graysky2** [comment]
Yes, I don't know how to avoid this as it is the expected behavior in bash when sourcing a file...

**Comment by graysky2** [comment]
I have attempted to address this in https://github.com/graysky2/profile-sync-daemon/commit/22154ea234a6e8b7634704046c56e2df35f463ba
