### ISSUE TITLE
Qutebrowser support

### ISSUE THREAD

**Issue by doctordrau** [graysky2/profile-sync-daemon#167]
Do you plan to support Qutebrowser?

**Comment by doctordrau** [comment]
Do you plan to support Qutebrowser?

**Comment by graysky2** [comment]
Never heard of it.  Does it have a sizable profile directory like chromium and firefox?  There is little benefit if not.

**Comment by doctordrau** [comment]
It is similar to luakit or dwb (working directory ~/user/.cache and ~/user/.config) with the difference that is based on PyQt5.It works quite quickly and i'm also not sure whether there is a benefit in this.

**Comment by graysky2** [comment]
Can you tell me how large ~/.config/foo is for your browser?  Managing cache is out-of-scope for psd, see the manpage for suggestions there... basically just mount it to tmpfs.

**Comment by doctordrau** [comment]
It does not affect the size ~/.config/foo.Ok, I'll mount it to tmpfs or try Anything-sync-daemon, maybe it can improve performance or may be not;)

**Comment by graysky2** [comment]
Can you tell me how the size of your profile dir which I understood to be ~/.config/something

**Comment by doctordrau** [comment]
`~/.config/qutebrowser`  - 76 kib size on disk ( but its just bookmarks and conf)
`~/.local/share/qutebrowser` - is folder that stores  local-storage ; sessions; offline-storage etc.Size respectively dynamically changing..
and i find ~/.cache/qutebrowser - 49 mib -some more files
It's  when opened 44 tabs
 I do not see anything interesting in `~/.config/qutebrowser`

**Comment by graysky2** [comment]
OK, I am guessing that the relevant sync target is in fact `~/.local/share/qutebrowser` which isn't formally cache since you have a discrete `~/.cache/qutebrowser` as well.  How large is `~/.local/share/qutebrowser` on average and are you recommending that it be the sync target?

**Comment by doctordrau** [comment]
`~/.local/share/qutebrowser` - 13 mib 

>  are you recommending that it be the sync target?

No, it was the default.But you can specify a destination folder if desired in qutebrowser.conf

**Comment by graysky2** [comment]
Well, if that is the default location, and if you are requesting support for it, you probably want to leave it defaulted!  Let me look into it for you.

**Comment by doctordrau** [comment]
if I understand you correctly and you mean to add support.I will be grateful to you.

**Comment by graysky2** [comment]
Please try https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.22
