### ISSUE TITLE
create tmpfs ram disk in home directory rather than /tmp

### ISSUE THREAD

**Issue by millerthegorilla** [graysky2/profile-sync-daemon#168]
I want to use my browsers with [firejail](https://github.com/netblue30/firejail/), but firejail is unable to support symlinks to /tmp due to security risks.

Is it possible to configure psd to create the ramdisk in the home directory?  Will using overlayfs achieve this or does overlayfs use symlinks?

Many thanks

**Comment by graysky2** [comment]
Not sure about firejail.  Creating the ramdisk within the homedir is outside the scope of how psd is designed to work.
