### ISSUE TITLE
psd.conf spoofed?

### ISSUE THREAD

**Issue by millerthegorilla** [graysky2/profile-sync-daemon#169]
ls -al ~/.config/psd/
total 32
drwxrwxr-x  2 james james 4096 May 21 17:14 .
drwxr-xr-x 27 james james 4096 May 21 17:12 ..
-r--------  1 james james  586 May 21 17:12 .psd.conf
-rw-r--r--  1 james james 1542 May 21 17:04 psd.conf

The contents of .psd.conf

```
# Automatically generated file; DO NOT EDIT!
# The purpose is to snapshot the settings used when psd was activated.
# Any edits to the live config: /home/james/.config/psd/psd.conf
# will be applied the _next_ time psd is activated.
#
USE_OVERLAYFS=""
BROWSERS="chromium chromium-dev conkeror.mozdev.org epiphany firefox firefox-trunk google-chrome google-chrome-beta google-chrome-unstable heftig-aurora icecat inox luakit midori opera opera-beta opera-developer opera-legacy opera-next otter-browser palemoon qupzilla rekonq seamonkey surf vivaldi vivaldi-snapshot"
USE_BACKUPS="yes"
```

When I query psd using 'psd p' firefox starts up.  I tried removing google-chrome from psd.conf and restarted psd but 'psd p', which only shows in terminal after I close the firefox window down that opens when I run the command, still shows that it is managing firefox and chrome.

thanks.

**Comment by graysky2** [comment]
I do not understand why/how firefox would load when you run `psd p` ... please try this:

1) Stop psd `systemctl --user stop psd`
2) Edit the BROWSERS array in `~/.config/psd/psd.conf` to have only google-chrome and firefox in it (quote them).
3) Post the output of `psd p` to this task.
4) No start psd `systemctl --user start psd`

Does everything work as expected?

**Comment by graysky2** [comment]
Any word?

**Comment by graysky2** [comment]
See https://github.com/graysky2/profile-sync-daemon/issues/166
