### ISSUE TITLE
firefox doesn't save session

### ISSUE THREAD

**Issue by mattia-b89** [graysky2/profile-sync-daemon#170]
sometimes (I noticed this problem three times in twenty days) FF starts with an old session.
e.g. tabs that have been closed in the previous session, they are yet opened

`psd p` output:
http://pastebin.com/k1HRk4T9
`psd.conf`:
http://pastebin.com/gn30Zwyz

Let me know whatelse you need!

**Comment by graysky2** [comment]
Your config and output look normal.  What you're describing seems like, for whatever reason, psd isn't resyncing.  Do you know that when this occurred, the system was shutdown gracefully?

**Comment by mattia-b89** [comment]
sometimes I have to wait 1m30s in order to power off my pc.
...systemd is waiting something but I can't read the name of the process, because screen goes black!!!
fortunately this happens only twice per month, but next time it happens, I'll check if it influences firefox session

**Comment by graysky2** [comment]
Yeah, I get that too... for me it's usually lxdm.  You can find an open task against systemd for this issue.  If your data loss coincides with the ungraceful shutdown, it is not psd's fault.  Whatever is hung is likely hung before psd can resync so it stands to reason that you lose the last <60 min of data.

**Comment by mattia-b89** [comment]
Yes, you are right!
I haven't idea about `psd` works (where can I find this information?), but
why don't sync profile even at the browser closure?

**Comment by graysky2** [comment]
If something is hung and systemd kills it after 90s, killing it could also kill psd or your filesystem etc. before the sync back is allowed to happen.  Is there anything relevant in your journal when such a shutdown is forced?

**Comment by mattia-b89** [comment]
At the moment, I can't examine extensively the journal due to corruption (I
think is corrupted) that makes me unable to choose between boots...
`journalctl --list-boots` reports an error (and this issue can be related
just to the "first" one...!!!).
Anyway I'll keep you up to date.

sent from my E2

**Comment by graysky2** [comment]
At this time, my interpretation of evidence is that the problem is not the fault of psd.  Feel free to request a re-open if you generate data that contradicts with this in the future.
