### ISSUE TITLE
/etc/psd.conf in ubuntu 16.04 not exists

### ISSUE THREAD

**Issue by kazelsama** [graysky2/profile-sync-daemon#171]
as title /etc/psd.conf in ubuntu 16.04 it was not created.

**Comment by graysky2** [comment]
This is the expected behavior: https://github.com/graysky2/profile-sync-daemon#note-for-version-6

**Comment by kazelsama** [comment]
Where i can copy a config for create "~/.psd/psd.conf"?

**Comment by graysky2** [comment]
This will be created for you when you load psd the first time.  Please see the man page.

**Comment by kazelsama** [comment]
Excuse yesterday was a long day, thanks for the patience :)
