### ISSUE TITLE
what repo to use for debian testing?

### ISSUE THREAD

**Issue by jonpolak** [graysky2/profile-sync-daemon#174]
If I'm on debian testing (current kernel 4.6) should I be pointing to vivid? xenial? yakkety?

**Comment by graysky2** [comment]
Just hit xenial.  FYI -- Jan Naumann from Debian has officially included PSD in the Debian repos.

https://packages.debian.org/unstable/profile-sync-daemon
https://tracker.debian.org/pkg/profile-sync-daemon

**Comment by jonpolak** [comment]
To be included in the debian repo is a huge deal! People that know their
stuff think you're doing great work!

**Comment by graysky2** [comment]
I was surprised as well :grin: 

It is also supplied by fedora and gentoo.

**Comment by JanLuca** [comment]
FYI: The current version 6.25 is already in Debian unstable, it should migrate to testing in a few days (there is a 10 days waiting period to avoid obvious bugs in testing). I also asked the backports people if they can import the package into jessie-backports so Debian stable users can easy use the package, too.

@graysky2: I was pleasantly surprised that the Ubuntu people imported (automatically?) the Debian packages for the next Ubuntu 16.10: https://launchpad.net/ubuntu/+source/profile-sync-daemon

**Comment by graysky2** [comment]
@JanLuca - That's great!  I can drop it from my PPA.

**Comment by graysky2** [comment]
Looks like psd is now live in Debian sid.
