### ISSUE TITLE
tmpfs dir does not exist

### ISSUE THREAD

**Issue by terminalmage** [graysky2/profile-sync-daemon#176]
```
% psd p
Profile-sync-daemon v6.25 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs technology is currently inactive.

Psd will manage the following per /home/erik/.config/psd/psd.conf:

 browser/psname:  chromium/chromium
 owner/group id:  erik/1000
 sync target:     /home/erik/.config/chromium
 tmpfs dir:       /run/user/1000/erik-chromium
 profile size:    449M
 recovery dirs:   none
% ls -l /run/user/1000/erik-chromium
ls: cannot access '/run/user/1000/erik-chromium': No such file or directory
```

Is this a case where I need to launch chromium using ``--disk-cache-dir=/run/user/1000/erik-chromium`` to match the location that psd is targeting?

**Comment by graysky2** [comment]
No.  Something odd happened where the tmpfsdir has been removed.  Stop psd.  Is /run/user/1000 full?  Your profile is pretty big.  If you have extra memory, you can allocate additional space to tmpfs as shown in the psd manpage... see Q4 in the FAQ section.

Additionally, you might consider cleaning your profile with profile-cleaner (in the AUR).

**Comment by terminalmage** [comment]
profile-cleaner cleaned 0.5 MB. I was able to clear another 75 MB or so by removing extensions I no longer use, my profile size is now 373MB. My tmpfs is nowhere near being full.

```
% df -h | fgrep /run/user/1000
tmpfs                 1.6G  374M  1.2G  24% /run/user/1000
```

I did however notice a pidfile for psd that was zero-size. The systemd journal shows the following message:

```
Jul 29 19:17:10 tardis profile-sync-daemon[32072]: No status data could be sent: $NOTIFY_SOCKET was not set
```

Digging into sd_notify documentation right now to find out what's misconfigured where, seems to be on my end.

**Comment by graysky2** [comment]
> I did however notice a pidfile for psd in /run/user/1000 that was zero-size.

That is expected (just an empty file).

I also get a line similar to your:
```
Jul 30 04:13:55 easy profile-sync-daemon[661]: No status data could be sent: $NOTIFY_SOCKET was not set
```

**Comment by terminalmage** [comment]
OK, it raised suspicion because pid files typically contain PIDs.

So I guess I'm back to square one.

**Comment by graysky2** [comment]
I am goign to close this since it's referencing #177 and since the 0-byte pid file is expected.
