### ISSUE TITLE
$NOTIFY_SOCKET was not set

### ISSUE THREAD

**Issue by christian-raedel** [graysky2/profile-sync-daemon#177]
Hi,

my journal shows a message about an unset socket. However syncing seems to be successful. I couldn't identify this message as error or warning. Is this something optional useful? 

    profile-sync-daemon[21735]: No status data could be sent: $NOTIFY_SOCKET was not set
    profile-sync-daemon[21735]: firefox resync successful
    profile-sync-daemon[21735]: chromium resync successful

Regards,
Christian

**Comment by graysky2** [comment]
I get the same in mine but with no ill effects... similar to #176 as well.
