### ISSUE TITLE
How is profile-sync-daemon different from anything-sync-daemon?

### ISSUE THREAD

**Issue by mindstormer12** [graysky2/profile-sync-daemon#180]
How is profile-sync-daemon different from anything-sync-daemon? From the [Arch Wiki entry]():

>  built in sanity checks for unique situations specific to running a browser profile in tmpfs. Anything-sync-daemon does not have these checks; under certain circumstances, browser profile data can be lost

but I'm curious what the specifics are that would require something more than what ASD offers. PSD seems like a subset of ASD but if it offers more than what ASD does, why isn't PSD suitable for all things ramdisk-related and that two very similar applications are created separately? Also, do how are these two applications preferable to other ramdisks and tools like vmtouch? 

Also, I suspect that profile-sync-daemon for Firefox users since Firefox allows you to disable disk cache and use memory cache, or does it still offer noticeable performances for the browser over running Firefox on an SSD?

Thank you and please forgive my ignorance.

**Comment by graysky2** [comment]
psd is tailored specifically to browser profiles, has checks to keep things sane when the browser is running, etc. whereas asd is really for sync targets.  Not sure about vmtouch or other tools you mention.  As to the cache dir, see the psd manpage:

> *Note that some browsers such as Chrome/Chromium, Firefox (since v21), Midori, and Rekonq actually keeps their cache directories separately from their browser profile directory. It is not within the scope of profile-sync-daemon to modify this behavior; users wishing to relocate this directory, may refer to the following url for several work-arounds: https://wiki.archlinux.org/index.php/Chromium_Tips_and_Tweaks#Cache_in_tmpfs
