### ISSUE TITLE
Unable to install under fish shell

### ISSUE THREAD

**Issue by Alsan** [graysky2/profile-sync-daemon#181]
When I install the daemon under fish shell, I got these messages.

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages have been kept back:
>   nvidia-prime-applet
> 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Setting up profile-sync-daemon (6.23-1) ...
> Unsupported use of '='. To run 'systemctl' with a modified environment, please use 'env XDG_RUNTIME_DIR=/run/user/$UID systemctl…'
> fish: XDG_RUNTIME_DIR=/run/user/$UID systemctl --user daemon-reload
>       ^
> dpkg: error processing package profile-sync-daemon (--configure):
>  subprocess installed post-installation script returned error exit status 127
> Errors were encountered while processing:
>  profile-sync-daemon
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 

Environment info:
- OS: Linuxmint 18
- Shell: Fish 2.2.0

**Comment by prajnak** [comment]
I have this same issue. I tried installing it from bash, and got the same error. Installed with bash after changing my $SHELL environment variable also to bash, and the issue still occurs

**Comment by dthul** [comment]
I have the same issue and created a pull request that should fix it.

**Comment by graysky2** [comment]
Thanks for the PR, @dthul and to you @prajnak for reporting.  I should really remove the debian scripts as they were my attempt to provide a package for Ubuntu and Debian.  Now that psd is included in the Debian/Ubuntu repos, I think far more experienced people are able to handle the needed code for apt/aptitude.  I will merge... do either of you have the inclination to check:

1) The Ubuntu/Debian package is in fact using my code for the packaging.
2) If not, reporting this upstream to their package maintainer.

**Comment by dthul** [comment]
It looks like [Ubuntu's version of the package](http://packages.ubuntu.com/yakkety/profile-sync-daemon) doesn't come with these scripts at all, not even in a modified version.

**Comment by dthul** [comment]
Neither do Debian's as far as I can tell.

**Comment by graysky2** [comment]
@dthul - I am not an expect with apt but I would think these or equivalents would be needed by that package manager.  Would you be kind enough to raise the issue with the Debian or Ubuntu packager maintainer?

**Comment by dthul** [comment]
Yes, I'll ask the maintainer.

**Comment by graysky2** [comment]
Thanks, closing but post back with a link if you used the bug tracker or just update if private email.

**Comment by dthul** [comment]
The package maintainer told me that he does not use your Debian scripts since he does not like the way they start/stop user services without asking the user.
I am not totally sure what exactly he means since I can't see any service starts/stops in these scripts except for the profile-sync-daemon itself of course.

**Comment by graysky2** [comment]
@dthul - I am ignorant to the official Debian policies on package triggered start/stops of services, but there have been cases in the past where internals in psd have changed that requires a pre-upgrade stop or else bad things would happen.

**Comment by dthul** [comment]
Do you think future versions will need a service restart? If so it should probably be part of the package.
I know that other package updates (like servers or databases) will also trigger a daemon restart.

**Comment by graysky2** [comment]
I don't plan on any but I can't rule it out either.  Debian absolutely has the facility for apt triggered actions (this is how I did it).
