### ISSUE TITLE
Debian bash 4.4 bad substitution

### ISSUE THREAD

**Issue by licaon-kter** [graysky2/profile-sync-daemon#182]
FYI

Debian Sid 64 bit, w/ bash 4.4-1 yields this error and exits:
```
/usr/bin/profile-sync-daemon: line 359: ${#DIRArr[@]##*/}: bad substitution
```

Downgrading to bash 4.3-15 fixes it.

Looking at the update: http://git.savannah.gnu.org/cgit/bash.git/diff/subst.c?h=bash-4.4&id=a0c0a00fc419b7bc08202a79134fcd5bc0427071 this might be at fault ( the way **@** is treated):

```
@@ -104,10 +103,13 @@ extern int errno;
 #define WRPAREN		L')'
 #endif
 
+#define DOLLAR_AT_STAR(c)	((c) == '@' || (c) == '*')
+#define STR_DOLLAR_AT_STAR(s)	(DOLLAR_AT_STAR ((s)[0]) && (s)[1] == '\0')
+
 /* Evaluates to 1 if C is one of the shell's special parameters whose length
    can be taken, but is also one of the special expansion characters. */
 #define VALID_SPECIAL_LENGTH_PARAM(c) \
-  ((c) == '-' || (c) == '?' || (c) == '#')
+  ((c) == '-' || (c) == '?' || (c) == '#' || (c) == '@')
 
 /* Evaluates to 1 if C is one of the shell's special parameters for which an
    indirect variable reference may be made. */
```

**Comment by graysky2** [comment]
Thanks for the heads-up... Arch has not yet pushed bash-4.4 out even to our testing repo so I was unaware of this change.  Perhaps bash handles substitutions differently now?  Will need to check.

**Comment by graysky2** [comment]
@licaon-kter - I am not a C-coder... can you suggest an alternative syntax based on the new code or is the new code seen as a bug?

**Comment by licaon-kter** [comment]
Unfortunately, no. That's just an (un)educated guess, it might not be even that at fault, not to mention this @ thing touches more code than what I pointed too.

**Comment by graysky2** [comment]
>Did you get a chance to repro it on Arch?

No, since we are still on 	4.3.046-1 which has been flagged out-of-date on 	2016-09-15.

**Comment by ian-kelling** [comment]
See my pull request which fixes this.
