### ISSUE TITLE
psd will delete existing profile symlinks

### ISSUE THREAD

**Issue by ian-kelling** [graysky2/profile-sync-daemon#186]
If you already symlink your profile, simply running psd p, which the documentation gives the impression it won't do anything bad, will remove your symlink, making your browser fail to start.

**Comment by graysky2** [comment]
Interesting... Which browser are you using?  I would like to setup your example and testing.

**Comment by ian-kelling** [comment]
Firefox. Before I knew about psd, I symlinked my profile directory to somewhere else ~/.mozilla/firefox/profile -> /some/other/location. Then I installed psd, shut down firefox, ran psd p, started firefox, firefox broken.

**Comment by graysky2** [comment]
If you want to use psd, please consider editing `~/.mozilla/firefox/profiles.ini` and defining the path to your profile therein like this:
```
[Profile0]
Name=banking
IsRelative=0
Path=/path/to/3z9a7omu.profile
```

Symlinked profiles are not supported at this time... let me see how feasible it is to implement.  I will update the documentation and also consider having psd bail if it detects a symlinked starting point.  Thank you for reporting.

**Comment by ian-kelling** [comment]
Thanks
