### ISSUE TITLE
psd causes problem with pam_systemd

### ISSUE THREAD

**Issue by tobanw** [graysky2/profile-sync-daemon#187]
After installing `psd` on Arch Linux from AUR (version 6.26-1, default blank config), I'm getting [this problem](https://bbs.archlinux.org/viewtopic.php?id=217666) after rebooting. It seems that the `psd` systemd unit is somehow interfering with `pam_systemd` on startup. Disabling the `psd` service solves the problem, though I don't understand how it causes it.

Looking through the journal I didn't see any problems on startup. The first result for "profile-sync-daemon" in `journalctl -xe` after a reboot looks fine:

```
Oct 05 11:50:26 archovo systemd[956]: Started Timer for profile-sync-daemon - 1Hour.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
```

Also, `psd` seems to be working fine. A typical block sync shows up in the journal as:

```
-- Unit UNIT has begun starting up.
Oct 05 16:32:48 archovo profile-sync-daemon[3237]: No status data could be sent: $NOTIFY_SOCKET was not set
Oct 05 16:32:48 archovo profile-sync-daemon[3237]: qutebrowser resync successful
Oct 05 16:32:48 archovo profile-sync-daemon[3237]: chromium resync successful
Oct 05 16:32:49 archovo profile-sync-daemon[3237]: firefox resync successful
Oct 05 16:32:49 archovo systemd[956]: Started Timed resync.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
```

Any ideas on what could be causing this?

**Comment by graysky2** [comment]
I missed the bbs post you referenced... I want to try and replicate this on my system so I can debug.  What do you have enabled for system service?
```
find /etc/systemd/system -mindepth 1 -type d | sed '/getty.target/d' | xargs ls -gG --color
find $HOME/.config/systemd/user -mindepth 1 -type d | xargs ls -gG --color
```

**Comment by tobanw** [comment]
Here are the outputs (with psd disabled). The `--color` flag was muddying the output with extra characters so I omitted it.

Output of `find /etc/systemd/system -mindepth 1 -type d | sed '/getty.target/d' | xargs ls -gG`:

```
/etc/systemd/system/bluetooth.target.wants:
total 0
lrwxrwxrwx 1 41 Mar 24  2015 bluetooth.service -> /usr/lib/systemd/system/bluetooth.service

/etc/systemd/system/multi-user.target.wants:
total 0
lrwxrwxrwx 1 39 Jun  4 18:40 devmon@toban.service -> /usr/lib/systemd/system/devmon@.service
lrwxrwxrwx 1 40 Feb 28  2016 dropbox@toban.service -> /usr/lib/systemd/system/dropbox@.service
lrwxrwxrwx 1 36 Mar 23  2015 fstrim.timer -> /usr/lib/systemd/system/fstrim.timer
lrwxrwxrwx 1 36 Jan 22  2016 garbageman.timer -> /etc/systemd/system/garbageman.timer
lrwxrwxrwx 1 42 Nov 30  2015 lm_sensors.service -> /usr/lib/systemd/system/lm_sensors.service
lrwxrwxrwx 1 46 Mar 24  2015 NetworkManager.service -> /usr/lib/systemd/system/NetworkManager.service
lrwxrwxrwx 1 40 Apr 19  2015 remote-fs.target -> /usr/lib/systemd/system/remote-fs.target
lrwxrwxrwx 1 35 Apr  3  2016 tlp.service -> /usr/lib/systemd/system/tlp.service

/etc/systemd/system/sleep.target.wants:
total 0
lrwxrwxrwx 1 35 Mar 29  2016 resume@toban.service -> /etc/systemd/system/resume@.service
lrwxrwxrwx 1 41 Apr  3  2016 tlp-sleep.service -> /usr/lib/systemd/system/tlp-sleep.service

/etc/systemd/system/sysinit.target.wants:
total 0
lrwxrwxrwx 1 49 May 10  2015 systemd-timesyncd.service -> /usr/lib/systemd/system/systemd-timesyncd.service
```

Output of `find $HOME/.config/systemd/user -mindepth 1 -type d | xargs ls -gG`:

```
total 0
lrwxrwxrwx 1 38 Oct  5 18:02 redshift.service -> /usr/lib/systemd/user/redshift.service
```

I already tried disabling the `redshift` unit, to no avail.

**Comment by graysky2** [comment]
Hmmm... would you mind some work to troubleshoot?  Can you disable the following, enable psd, then reboot and see if any are to blame?

```
bluetooth.service
devmon@toban.service
dropbox@toban.service
garbageman.time
NetworkManager.service
tlp.service
resume@toban.service
tlp-sleep.service
```

These are present on your system but not on mine and our goal is to identify what might be causing the issue which is unfortunately an exercise in trial and error.

**Comment by tobanw** [comment]
I disabled all of those, but no success. (Also upgraded to 6.27-1)

I forgot to mention before, but this only occurs when logging in after boot. If I log out and log back in, the problem goes away. I'm not using a display manager, I just run `startx` from `~/.zprofile`.

**Comment by graysky2** [comment]
Can you try from a display manager?  I am using lxdm so that's a pretty good place to start.

**Comment by graysky2** [comment]
Would you be willing to try the latest commit?  

1) Stop psd
2) Backup your profiles
3) The AUR contains [profile-sync-daemon-git](https://aur.archlinux.org/packages/profile-sync-daemon-git) which you can use to build r648.18955ef-1

**Comment by tobanw** [comment]
Still no luck with 6.28. I'll try with lxdm when I have some time later.

**Comment by graysky2** [comment]
> Still no luck with 6.28. I'll try with lxdm when I have some time later.

OK... the key diff in 6.28 is really for #177 but since I don't understand the cause of this report, figured it would be worth a try.

**Comment by tobanw** [comment]
`lxdm` solves the problem! Any idea why it fails without a DM?

Also, I tried booting up and just logging into the console (i.e., not calling `startx`), but still no luck.

**Comment by graysky2** [comment]
>lxdm solves the problem! Any idea why it fails without a DM?

Glad to hear that... it must be triggering systemd to setup the needed space whereas the console does not.  I am not expert with systemd to be able to answer that... just inspecting lxdm.service shows that it requires:

`After=systemd-user-sessions.service getty@tty1.service plymouth-quit.service`

So perhaps `systemd-user-sessions.service` is the key to it.  What happens if you stop lxdm, reboot, log into the console, manually start `systemd-user-sessions.service` then try your startx command?

**Comment by tobanw** [comment]
No dice, `systemd-user-sessions.service` was already active. In any case, the problem occurs before starting an X session. Immediately after entering my login creds at the console, my system hangs for ~30s. Once it gives me a shell, I can see that `XDG_RUNTIME_DIR` hasn't been set. So it has nothing to do with X.

**Comment by graysky2** [comment]
I'm not sure what might be the cause :/

**Comment by soredake** [comment]
Me helped change pam_systemd from optional to required: 
```
sudo sed -i '/pam_systemd.so/d' /etc/pam.d/system-auth
su -c "printf 'session		required	pam_systemd.so' >> /etc/pam.d/system-auth"

```

**Comment by graysky2** [comment]
@soredake - On my box, `/etc/pam.d/system-auth` does not contain any lines referencing pam_systemd.so at all.

```
#%PAM-1.0

auth      required  pam_unix.so     try_first_pass nullok
auth      optional  pam_permit.so
auth      required  pam_env.so

account   required  pam_unix.so
account   optional  pam_permit.so
account   required  pam_time.so

password  required  pam_unix.so     try_first_pass nullok sha512 shadow
password  optional  pam_permit.so

session   required  pam_limits.so
session   required  pam_unix.so
session   optional  pam_permit.so
```

**Comment by tobanw** [comment]
Same here, mine is identical to @graysky2's.

**Comment by graysky2** [comment]
@tobanw - any update?

**Comment by olivermg** [comment]
I've been experiencing exactly the same problem: When logging in on the console, the login takes around 25 sec (dbus timeout as I've learned) and afterwards, `XDG_RUNTIME_DIR` is not set and pamd reports a session timeout (as `journalctl -xe` shows).

I've been able to track it down to the following:

- I noticed after the 25 sec timeout via `ps auxww` that the psd resync daemon searches for crashfiles in my `$HOME`. This takes a while (even on my SSD) as it seems to be searching the entire `$HOME`, which is around 200G in my case.

- Running `psd resync` manually shows the same behavior, but seemingly only for those browsers that I don't use. I'm using Chrome & Firefox and `psd resync` runs quick for these two, but it seems to scan my entire `$HOME` for all other browsers for which I don't have any config.

- Thus, I've tried setting `BROWSERS="google-chrome firefox"` to make psd ignore all other browsers and voila... the problem vanishes. So this is my workaround for now.

My wild guess is that logging in via console somehow causes psd to scan the entire `$HOME` for crash files instead of only looking in a specific location? Maybe some env var is missing in contrast to when one logs in via a DM?

I hope this turns out to be useful info.

**Comment by tobanw** [comment]
@olivermg: that's really interesting because I was using Qutebrowser in addition to Chromium and Firefox. I can't test it out at the moment (had a hardware failure and haven't repaired yet) but I'll check it out once I've got that machine back up and running.

**Comment by tobanw** [comment]
Finally got around to trying this -- still no luck. I tried setting `BROWSERS=firefox` but still got the 25s login delay and `XDG_RUNTIME_DIR` is not set.
