### ISSUE TITLE
Not fully compliant to the XDG Base Directory Specification

### ISSUE THREAD

**Issue by farsil** [graysky2/profile-sync-daemon#189]
While the daemon itself properly detects where the configuration files are, the issue is in the files in `common/browsers`. Check the contents of `chromium`, for example:

    DIRArr[0]="$homedir/.config/$browser"
    PSNAME="$browser"

It should make use of `$XDG_CONFIG_HOME` instead of relying on an hardcoded `.config` dir.

A temporary workaround is to symlink `.config` to `$XDG_CONFIG_HOME`.

Hope it was helpful.

**Comment by graysky2** [comment]
How does this commit look?  Seems to work fine on the few browsers I tested.

**Comment by farsil** [comment]
The commit seems fine, I've applied it on my system and it works.

Thank you :)
