### ISSUE TITLE
[enhancement 2/2] set a limit for backup

### ISSUE THREAD

**Issue by mattia-b89** [graysky2/profile-sync-daemon#191]
I'd like to have an option that limits the number of backups since they can have a large footprint on the disk.
the option can works with the mere number of backup or the maximum size of the backup folder.
this is just an idea. thank you for your big work!

**Comment by graysky2** [comment]
So I gave this a try, (see the following commit in the unstable branch), but it does not behave as it should in my tests.  The code should keep the most recent ones but it doesn't for me:
https://github.com/graysky2/profile-sync-daemon/commit/509ead681043822c70416e6cbfe2e76da41cccc7

**Comment by graysky2** [comment]
Implemented.

**Comment by mattia-b89** [comment]
thank you!
