### ISSUE TITLE
palemoon: symlink doesn't work

### ISSUE THREAD

**Issue by steelstrings** [graysky2/profile-sync-daemon#192]
the symlink to /run/user/1000/ for palemoon doesn't exist, but the folder in /run/user/1000/ does
and psd p states strange recovery dirs

```browser/psname:  palemoon/palemoon
owner/group id:  michael/100
sync target:     /home/michael/.moonchild productions/pale moon/g83a01x3.default
tmpfs dir:       /run/user/1000/michael-palemoon-g83a01x3.default
profile size:    71M
 recovery dirs:   3 <- delete with the c option
  dir path/size:  /home/michael/.moonchild ()
  dir path/size:  productions/pale ()
  dir path/size:  moon/g83a01x3.default-backup-crashrecovery-20161201_094446 ()
```

**Comment by graysky2** [comment]
Not sure what to tell you... works for me... you did look within `~/.moonchild productions/pale moon` yes?  Note the lame use of spaces.

```
Profile-sync-daemon v6.31 on Arch Linux

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs technology is currently inactive.

Psd will manage the following per /home/facade/.config/psd/.psd.conf:

 browser/psname:  palemoon/palemoon
 owner/group id:  facade/100
 sync target:     /home/facade/.moonchild productions/pale moon/9fxrcd7w.default
 tmpfs dir:       /run/user/1000/facade-palemoon-9fxrcd7w.default
 profile size:    12M
 recovery dirs:   none
```

**Comment by steelstrings** [comment]
Yes i checked the directory
What i did now was to try with a new profile, now it works

What i forgot to tell was, that palemoon crashed at a time, strangely after that all my tabs were literally empty, but i restored with my backup.
Since then it doesn't work, the folder exists in `/run/user/1000/` but it's empty.
I'm using a copy of my profile now, which works with psd

**Comment by graysky2** [comment]
Not sure how to make sense of what happened and tie it back to psd...
