### ISSUE TITLE
psd's systemd services does not work for me

### ISSUE THREAD

**Issue by ed-torvalds** [graysky2/profile-sync-daemon#193]
I am on Arch Linux running GNOME 3. I have installed latest profile sync daemon from AUR.  
I have enabled `psd.service` as `systemctl --user enable psd.service` but not only it does not starts on my system boot, it also prevents me from logging in GNOME. Even though after some tries I get to login, my system behaves weird i.e. some functionalities of my desktop like sound don't work.  
If disable it and restart my system and start `psd.service` as `systemctl --user start psd.service` it won't 'unsync' my firefox profile before shutdown or reboot. When I start my system, I find that firefox profile folder is missing from `~/.mozilla/firefox` and there is a broken symlink by the name of profile folder linked to `/dev/null`.  
What do I do get this thing working as described on arch wiki page of its?  
Thanks, please ask for any information you need.

**Comment by graysky2** [comment]
Any encryption on your system or a is it a pretty setup?
1) Disable psd `systemctl --user disable psd`
2) Post the output of `psd p`

**Comment by ed-torvalds** [comment]
I have already disabled `psd` service, now I am manually starting it and stopping it using `systemctl`

       % psd p
    Profile-sync-daemon v6.31 on Arch Linux

     Systemd service is currently active.
     Systemd resync-timer is currently active.
     Overlayfs technology is currently inactive.
    
    Psd will manage the following per /home/edward/.config/psd/.psd.conf:
    
    browser/psname:  firefox/firefox
    owner/group id:  edward/1000
    sync target:     /home/edward/.mozilla/firefox/86pg2hi9.default
    tmpfs dir:       /run/user/1000/edward-firefox-86pg2hi9.default
    profile size:    497M
    recovery dirs:   1 <- delete with the c option
    dir path/size:  /home/edward/.mozilla/firefox/86pg2hi9.default-backup-crashrecovery-20161209_004528 (500M)

**Comment by graysky2** [comment]
The output you show above looks normal.  I'm not sure what would cause what you've described.  You're currently running psd from the output above.  If you stop it, does it behave as expected?  Is this problem only on login?

**Comment by ed-torvalds** [comment]
Yes, this problem occurs only on login. Please see this image below, in this case I have enabled `psd` (`systemctl --user enable psd`), and have rebooted and logged-in on tty (mainly to see errors on stdout)
![export](https://cloud.githubusercontent.com/assets/15322797/21182465/4ab9b130-c229-11e6-98f5-20fc3b443bc3.jpeg)

Instead of logging-in on tty if I login with gnome, which I can't and I face problems described in question.  
Because of this problem I use `psd` by starting and stopping manually and not by enabling it.

**Comment by graysky2** [comment]
It's like the loginmanager is starting some component of systemd that is making expected directories.  Is logind running when you login from the shell?

`systemctl status systemd-logind`

**Comment by graysky2** [comment]
Ping?

**Comment by ilusi0n** [comment]
Hello, I have the exactly same problem
The output of `systemctl status systemd-logind` is the following
```
 systemd-logind.service - Login Service
   Loaded: loaded (/usr/lib/systemd/system/systemd-logind.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2017-06-16 10:24:14 WEST; 4min 48s ago
     Docs: man:systemd-logind.service(8)
           man:logind.conf(5)
           http://www.freedesktop.org/wiki/Software/systemd/logind
           http://www.freedesktop.org/wiki/Software/systemd/multiseat
 Main PID: 700 (systemd-logind)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/systemd-logind.service
           └─700 /usr/lib/systemd/systemd-logind

Jun 16 10:24:12 Suzie systemd[1]: Starting Login Service...
Jun 16 10:24:14 Suzie systemd-logind[700]: New seat seat0.
Jun 16 10:24:14 Suzie systemd[1]: Started Login Service.
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event5 (Power Button)
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event8 (Video Bus)
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event2 (Power Button)
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event3 (Lid Switch)
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event4 (Sleep Button)
Jun 16 10:24:14 Suzie systemd-logind[700]: Watching system buttons on /dev/input/event7 (Video Bus)
Jun 16 10:24:26 Suzie systemd-logind[700]: New session c1 of user ilusi0n.
```

Any ideias?

**Comment by graysky2** [comment]
Ping again.  @ilusi0n @ed-torvalds

**Comment by ed-torvalds** [comment]
Thanks for your help, not to mention this software. I cannot help I am not on arch anymore.

**Comment by AlexeyGusev** [comment]
similar problem on ubuntu 18.04
enabling service with `systemctl --user enable psd` doesn't help, no automatic startup, must run  `systemctl --user start psd` manually after every login.

I even tried `--enable psd-resync` because `psd.service` file says this:
```
# just call /bin/true and let psd-resync.service do it
ExecStart=/bin/true
```
but still no luck, despite the fact that correct symlinks are created: 
```
$ ls -la .config/systemd/user/default.target.wants/psd*
.config/systemd/user/default.target.wants/psd-resync.service  -> /usr/lib/systemd/user/psd-resync.service
.config/systemd/user/default.target.wants/psd.service -> /usr/lib/systemd/user/psd.service
```

**Comment by graysky2** [comment]
So you enabled the user service.  When you boot the machine and psd is not started by systemd, what relevant output in journalctl is there?

**Comment by AlexeyGusev** [comment]
> So you enabled the user service. When you boot the machine and psd is not started by systemd, what relevant output in journalctl is there?

After reboot, `journalctl --user --unit=psd` shows nothing, but then if you start psd manually (`systemctl --user start psd`), you get these lines:
```
DATE HOSTNAME systemd[2453]: Starting Profile-sync-daemon...
DATE HOSTNAME systemd[2453]: Started Profile-sync-daemon.

```
when you forget to start service manually, `journalctl --user --unit=psd-resync` generates a lot of noise, complaining that it cannot overwrite a default-backup profile folder by a file and that it cannot create` <profile_folder>/null` link because it exists, and reports successful resync if psd service is up:
```
DATE HOSTNAME systemd[2453]: Starting Timed resync...
DATE HOSTNAME profile-sync-daemon[3730]: firefox sync successful
DATE HOSTNAME systemd[2453]: Started Timed resync.
```

**Comment by skerit** [comment]
So I had the same problem, and in the logs I saw this:

```
profile-sync-daemon[19083]: Refusing to start; epiphany is running by skerit!
```

Even though the epiphany browser was **not** running, `/usr/lib/epiphany-search-provider` was. I guess it's something Gnome-shell starts automatically now?

I killed it and afterwards psd started working correctly.

Maybe psd doesn't need to be so strict, as I didn't even enable epiphany in the config.

**Comment by graysky2** [comment]
If you define your `BROWSERS=` in `psd.conf` and if you do not include epiphany there, psd will not do the check.  I only default to the check if nothing is supplied.  Maybe a better strategy is to either
1. either force the user to define the browser or
2. come up with a more robust strategy for determining if it's running

I think number 1 is more appealing...

**Comment by graysky2** [comment]
@skerit - In the case of epiphany, pgrep is keying on the partial match in /usr/lib/epiphany-search-provider which is a false positive as you pointed out.   I actually thought https://github.com/graysky2/profile-sync-daemon/commit/e471c0d666672aad83cd3d65261463a37c3361f3 would prevent this.  What version of psd are you running?

**Comment by graysky2** [comment]
@skerit - Would you mind trying https://github.com/graysky2/profile-sync-daemon/commit/cc5bb3af2767dc9e695212a4bd449231b3caa398 and reporting back?  Seems to work in my test cases.
