### ISSUE TITLE
Any chance to include cache handling?

### ISSUE THREAD

**Issue by edgard** [graysky2/profile-sync-daemon#194]
First of all, thanks a lot for this, it works wonderfully for me, question is, just as a quality of life improvement, is it possible to include cache directory handling? I know I can just symlink, it's just that I use on multiple machines with automated install and it's really easy to forget to symlink since the profile name is random (for firefox at least).

**Comment by graysky2** [comment]
Sorry, I have no plans to cover cache since psd supports so many different products.
