### ISSUE TITLE
google-chrome multiple profiles ?

### ISSUE THREAD

**Issue by niksfirefly** [graysky2/profile-sync-daemon#195]
Is it possible to use psd with multiple google-chrome profiles?
i mean multiple instances google-chrome run with --user-data-dir

thx

**Comment by graysky2** [comment]
Never tried multiple profiles... psd is currently looking to `~/.config/google-chrome` ... I assume you can define the --user-data-dir anywhere?

**Comment by niksfirefly** [comment]
what do you mean anywhere?
google-chrome has CLI option --user-data-dir for profile, i think firefox has similar
I assume that without patch for psd it is not possible at the time?
thx

**Comment by graysky2** [comment]
>what do you mean anywhere?

Meaning you can define the location anywhere your user has rwx... `/foo/bar` or the like.

> I assume that without patch for psd it is not possible at the time?

Correct, psd expects a single directory (see `/usr/share/psd/browsers`).
