### ISSUE TITLE
psd exiting uncleanly breaks entire OS desktop session

### ISSUE THREAD

**Issue by tidux** [graysky2/profile-sync-daemon#197]
If psd does not exit cleanly, it will fail to start when invoked automatically by systemd's user-session.  This will in turn cause systemd's user-session to time out, triggering a systemd bug (issue already open) which crashes, thus rendering anything that depends on a user DBus session utterly broken until the psd problem is resolved and the system is restarted.  This means that psd should forcibly blow away any unclean state as the very first thing it does after reading the config file.

**Comment by graysky2** [comment]
Can you describe the condition that will cause psd to "not exit cleanly?"  Can you also reference the bug you mentioned?

**Comment by tidux** [comment]
https://github.com/systemd/systemd/issues/2863

I've seen power loss during operation leave multiple incomplete copies of my Firefox profile in ~/.mozilla, although oddly enough not for Firefox Developer Edition.

**Comment by chaserhkj** [comment]
Confirmed this behavior on Arch Linux with systemd v232 and psd v6.31

Generally this bug in systemd occurs when any of the user units takes too long, and that would happen to psd if there's an unclean exit. And the bug would break the session control and cause any user application making use of DBus to malfunction.

**Comment by graysky2** [comment]
Not sure what can be done in psd if the problem lies with systemd.

**Comment by soredake** [comment]
I experience the same, seems to fixed in master https://github.com/systemd/systemd/commit/0c2826c60c508a0300f9978ae3818d6f4c00d53a
