### ISSUE TITLE
Please add support for Iridium and Ungoogled-Chromium browser

### ISSUE THREAD

**Issue by nick-s-b** [graysky2/profile-sync-daemon#198]
Hi all,

Iridium is a privacy-oriented browser based on Chromium code base.  More info here:
https://iridiumbrowser.de/

Ungoogled-Chromium is in a similar vein and it too is all about removing all the Google hooks from Chromium. More info here:
https://github.com/Eloston/ungoogled-chromium

Bot hare available in AUR as binaries and source packages.

Thanks!

**Comment by graysky2** [comment]
I don't want to officially support niche browsers any more.  You can add a file to `/usr/share/psd/browsers/` to support either of these.  Just take a look at the examples in there.
