### ISSUE TITLE
Issue with it and Opera Next (12.15)

### ISSUE THREAD

**Issue by Zero3K** [graysky2/profile-sync-daemon#199]
Its not saving  and restoring Opera Next's automatically generated sessions file. When I exit it with a bunch of tabs open, then relaunch it and load the previous session, I end up with two blank tabs (not all the tabs that were opened when I closed it).

**Comment by graysky2** [comment]
I can't reproduce using opera 42.0.2393.517.  What is the output of `psd p`

**Comment by Zero3K** [comment]
osboxes@osboxes:~$ psd p
Profile-sync-daemon v6.31 on Ubuntu 16.04 LTS

 Systemd service is currently active.
 Systemd resync-timer is currently active.
 Overlayfs v23 is currently active.

Psd will manage the following per /home/osboxes/.config/psd/.psd.conf:

find: ‘/home/osboxes/.config/Thunar’: Permission denied
find: ‘/home/osboxes/.cache/dconf’: Permission denied
find: ‘/home/osboxes/.gvfs’: Permission denied
find: ‘/home/osboxes/.dbus’: Permission denied
 browser/psname:  opera/opera
 owner/group id:  osboxes/1000
 sync target:     /home/osboxes/.opera
 tmpfs dir:       /run/user/1000/osboxes-opera
 profile size:    4.0K
 overlayfs size:  4.0K
 recovery dirs:   2 <- delete with the c option
  dir path/size:  /home/osboxes/.opera-next-backup-crashrecovery-20170203_213858 (274M)
  dir path/size:  /home/osboxes/.mozilla/firefox/l4hwpbuo.default-backup-crashrecovery-20170203_213857 (17M)

 browser/psname:  firefox/firefox
 owner/group id:  osboxes/1000
 sync target:     /home/osboxes/.mozilla/firefox/l4hwpbuo.default
 tmpfs dir:       /run/user/1000/osboxes-firefox-l4hwpbuo.default
 profile size:    17M
 overlayfs size:  0
 recovery dirs:   1 <- delete with the c option
  dir path/size:  /home/osboxes/.mozilla/firefox/l4hwpbuo.default-backup-crashrecovery-20170203_213857 (17M)

find: ‘/home/osboxes/.config/Thunar’: Permission denied
find: ‘/home/osboxes/.cache/dconf’: Permission denied
find: ‘/home/osboxes/.gvfs’: Permission denied
find: ‘/home/osboxes/.dbus’: Permission denied
 browser/psname:  opera-next/opera-next
 owner/group id:  osboxes/1000
 sync target:     /home/osboxes/.opera-next
 tmpfs dir:       /run/user/1000/osboxes-opera-next
 profile size:    902M
 overlayfs size:  666M
 recovery dirs:   2 <- delete with the c option
  dir path/size:  /home/osboxes/.opera-next-backup-crashrecovery-20170203_213858 (274M)
  dir path/size:  /home/osboxes/.mozilla/firefox/l4hwpbuo.default-backup-crashrecovery-20170203_213857 (17M)

osboxes@osboxes:~$ ^C
osboxes@osboxes:~$

**Comment by graysky2** [comment]
Seems in order with the exception of the permission denied errors.... as root:
`chown -R osboxes:YOURGROUP /home/osboxes`

I don't think those are to blame for the behavior you're seeing though.  On my system, the tabs in opera are restored just fine.

**Comment by Zero3K** [comment]
Are you using the same version of Opera as me?

**Comment by graysky2** [comment]
> I can't reproduce using opera 42.0.2393.517.

You haven't provided an opera version, just stated opera-next.  I don't see a PKGBUILD for opera-next for my distro to test.

**Comment by Zero3K** [comment]
https://bitbucket.org/prestocore-fan/presto and https://github.com/PrestoXen/openopera-patches ;)

**Comment by graysky2** [comment]
Is this still an issue?

**Comment by Zero3K** [comment]
I am no longer using it on Linux.
