### ISSUE TITLE
Install old version (5.50) in Ubuntu 14.04

### ISSUE THREAD

**Issue by cipri-tom** [graysky2/profile-sync-daemon#200]
Hi,

I saw that `upstart`  is no longer supported. 
However, version `5.50` used to be able to run with upstart.

Would it be possible to install version `5.50` ? If so, what are the risks associated with being on an older version ? Finally, do I have to build from source to get `5.50` ?

Many thanks,
Ciprian

**Comment by graysky2** [comment]
Lots of changes since 5.50... I recommend against it.  You can build from source/old versions are available by tags.
