### ISSUE TITLE
psd forces systemd on users

### ISSUE THREAD

**Issue by hasufell** [graysky2/profile-sync-daemon#201]
Why? It used to support even openrc. Now it's yet another thing I will not install on my system.

**Comment by graysky2** [comment]
Hello Julian.  Been a long time.  Hope you're well.  To answer your question: systemd has become ubiquitous; Arch, my primary distro, switched a few years ago as has Ubuntu/Debian/Fedora so I stopped fighting it and just learned systemd.  It is simply too much overhead for me to support multiple init systems.

**Comment by hasufell** [comment]
Arch isn't really the only distro out there. There are several distros that either have systemd optional (e.g. Gentoo, Exherbo, Funtoo) or don't have it at all as init system (e.g. Alpine Linux).

Also: it's in fact not mandatory on a lot of distros either, e.g. Arch or Manjaro either:
https://blog.notfoss.com/posts/openrc-on-arch-linux/
https://wiki.manjaro.org/index.php?title=OpenRC,_an_alternative_to_systemd

Also see
http://without-systemd.org/wiki/index.php/Main_Page#GNU.2FLinux_distributions

I also don't know what you mean with "overhead". The init scripts back then where pretty much all contributed by other people. It seems this project has gone anti-community too.

**Comment by graysky2** [comment]
With version 6 of psd, systemd is needed for state checks as you see in the code.  I'd like to offer more options to users, but again, my project time is limited and this change was sensible for me.

**Comment by ibrokemypie** [comment]
Um, Void linux, which is endorsed in the readme, is  currently on 5.75, and I cant find any info on how to configure it properly for pre-6 versions. I assume Void has not updated the package since it does not use systemd, instead using runit. Any assistance would be great
