### ISSUE TITLE
temporary disabling psd necessary to install firefox addon requiring restart

### ISSUE THREAD

**Issue by Konfekt** [graysky2/profile-sync-daemon#202]
For example the firefox addon https://addons.mozilla.org/fr/firefox/addon/https-everywhere/ requires a restart of firefox after upgrading it to the latest release.

With psd active, the addon will continue being listed as only availabe after a restart of firefox, even after a restart of firefox (several times). Instead, the only way to enable it and psd again is by

- quitting firefox, 
- disabling psd temporarily, `systemctl --user stop psd.service`, 
- then starting firefox
- then quitting firefox
- enabling pdf `systemctl --user start psd.service`, and
- starting firefox again.

This might relate to https://github.com/graysky2/profile-sync-daemon/issues/126

**Comment by graysky2** [comment]
Interesting... something with the addon must not like the symlink.  The best I can do is to document it in the man page.  I haven't run into this using chromium.

**Comment by Konfekt** [comment]
This has already been discussed at https://github.com/graysky2/profile-sync-daemon/issues/126

**Comment by Konfekt** [comment]
The solution at https://github.com/graysky2/profile-sync-daemon/issues/126 was to disable overlay-fs.

**Comment by Konfekt** [comment]
I can confirm that, as in https://github.com/graysky2/profile-sync-daemon/issues/126, disabling overlay-fs resolves the problems.

**Comment by Konfekt** [comment]
How about a note in the README and man page that for Firefox users, overlay-fs should only be enabled if one is sure not to install addons (such as muBlock Origin) ?

**Comment by rabin-io** [comment]
Not happening with Fedora (25) and MATE DE , just updated Greasymonkey and never had a problem with uBlock Origin as well .

**Comment by Konfekt** [comment]
As Firefox complains about missing permission to write while overlay-fs is enabled, perhaps `/etc/sudoers` is wrongly configured?

In the line
```
foo ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper
```
foo is the user name?

**Comment by graysky2** [comment]
Yes, foo is your user.

**Comment by Konfekt** [comment]
Strange. Perhaps under OpenSUSE 42.2 (in my case) additional access rights have to be granted for overlay-fs working properly. Would be interesting to know the distribution in https://github.com/graysky2/profile-sync-daemon/issues/126 as well

**Comment by Konfekt** [comment]
Well @neitsab 's distribution was Arch Linux.

**Comment by Konfekt** [comment]
This happened with psd 6.28. Now 6.31 is available. I cannot find a change log. Did the overlay-fs implementation change between these two versions?

**Comment by Konfekt** [comment]
Sorry, now I found https://github.com/graysky2/profile-sync-daemon/releases/tag/v6.28 and it seems that things persist.

**Comment by graysky2** [comment]
Is this still an issue?

**Comment by Konfekt** [comment]
Yes. It occurs with 6.31, and since then no commit changed the source code.

**Comment by graysky2** [comment]
I'm not sure why.... perhaps related to https://github.com/graysky2/profile-sync-daemon/issues/210 ... are you using overlayfs mode?  Any change in behavior switching in or out of it?

**Comment by Konfekt** [comment]
Ah, ok. Disabling overlayfs mode completely resolves it. No problem for months. Enabling it produces the issue discussed here.

**Comment by graysky2** [comment]
Although I am unsure what causes this, I will modify the docs to document it.  Thanks for the testing and the initial report.

**Comment by timofonic** [comment]
@graysky2 Any news?
