### ISSUE TITLE
psd doesn't detect Firefox config, in standard folder

### ISSUE THREAD

**Issue by finchd** [graysky2/profile-sync-daemon#205]
Ubuntu 16.04.2 LTS
psd v6.31 from graysky's PPA

```shell
$ psd preview
Profile-sync-daemon v6.31 on Ubuntu 16.04.2 LTS

Systemd service is currently active.
Systemd resync-timer is currently active.
Overlayfs v23 is currently active.

Psd will manage the following per /home/finchd/.config/psd/psd.conf:

browser/psname:  chromium/chromium
owner/group id:  finchd/1419772417
sync target:     /home/finchd/.config/chromium
tmpfs dir:       /run/user/1419894687/finchd-chromium
profile size:    135M
overlayfs size:  
recovery dirs:   none
```

It doesn't discover my Firefox, which is the one I want to use - chromium is my backup browser, my work requires FF

Running just the firefox detection script in debug mode, I see a strange thing:

```shell
$ bash -x /usr/share/psd/browsers/firefox
+ [[ -d /home/finchd/.mozilla/firefox ]]
+ profileArr=($(grep '[P,p]'ath= $HOME/.mozilla/firefox/profiles.ini |
   sed 's/[P,p]ath=//'))
++ sed 's/[P,p]ath=//'
++ grep '[P,p]ath=' /home/finchd/.mozilla/firefox/profiles.ini
+ index=0
+ PSNAME=
+ for profileItem in '${profileArr[@]}'
++ echo $'Profiles/0i7y7gr6.default\r'
++ cut -c1
+ [[ P = \/ ]]
+ DIRArr[index]=$'/home/finchd/.mozilla/firefox/Profiles/0i7y7gr6.default\r' 
+ index=0+1
+ check_suffix=1
```

"/home/finchd/.mozilla/firefox/Profiles/0i7y7gr6.default\r" The \r should probably be a carriage-return right? Having a literal '\r' there is probably breaking things? It isn't getting that from my profiles.ini though...

```profiles.ini
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=Profiles/0i7y7gr6.default
```

The profile itself is still there, no symlinks or anything, and the whole machine lives in a single partition.
What else should I look at?

**Comment by graysky2** [comment]
Not sure about that oddness with your profile.  Can you stop psd and manually rename the profile dir and also adjust it in profiles.ini?

**Comment by finchd** [comment]
When I get back to work, sure. What should I change it to? Move it out of the Profiles/ folder into .mozilla/firefox/ ?

**Comment by graysky2** [comment]
Is this still an issue?

**Comment by tidux** [comment]
Possibly related, psd fails to detect Firefox Dev Edition profiles at all.

**Comment by timofonic** [comment]
@finchd @tidux @graysky2 Any news?

**Comment by graysky2** [comment]
No response in 2+ years.  Reopen if still facing.
