### ISSUE TITLE
Add support for Brave browser

### ISSUE THREAD

**Issue by notuxius** [graysky2/profile-sync-daemon#207]
Based on Chromium, built-in Adblock and HTTPS Everywhere
Link to homepage - https://brave.com/

**Comment by graysky2** [comment]
You can easily copy `/usr/share/psd/browsers/chromium` to support this.

**Comment by brauliobo** [comment]
@graysky2 should I add the variables below to `.config/psd/psd.conf`? 

```
~ ❯❯❯ cat /usr/share/psd/browsers/chromium
DIRArr[0]="$XDG_CONFIG_HOME/$browser"
PSNAME="$browser"
```

**Comment by Rtizer-9** [comment]
> You can easily copy `/usr/share/psd/browsers/chromium` to support this.

Hi @graysky2 , I copied the text in this file and made a new file named brave-browser-nightly;  restarted psd, didn't work. I know this has been mentioned several times and your opinion on this, I also tried something by looking at text in firefox file too but that too didn't work. Can you please tell me exactly what I need to do.

Thanks
