### ISSUE TITLE
Cannot update uBlock Origin filters with PSD

### ISSUE THREAD

**Issue by matoro** [graysky2/profile-sync-daemon#210]
As described in the issue at https://github.com/gorhill/uBlock/issues/3018 , PSD causes filter updates in uBlock Origin to hang indefinitely.  Further information can be provided as needed.

**Comment by graysky2** [comment]
I don't have any experience with uBO.  If it expects certain permissions for example that the tmpfs doesn't provide, that may explain the hang you're encountering.  Are you running in overlayfs mode?  If yes, try disabling it.  If no, try enabling it.

**Comment by matoro** [comment]
@graysky2 So originally I did *not* have it enabled, as per the default.  Enabling it did fix the problem.  Closing this for now, thanks.
