### ISSUE TITLE
PSD not using option BACKUPLIMIT

### ISSUE THREAD

**Issue by eedrah** [graysky2/profile-sync-daemon#214]
VERSION: Profile-sync-daemon v6.31 on Ubuntu 17.04

EXPECTED BEHAVIOUR: When `BACKUP_LIMIT=1` in `$HOME/.config/psd/psd.conf`, the number of backuped profile directories should be 1.

ACTUAL BEHAVIOUR: There are more.

METHOD: I changed the `.conf` file. I confirmed the `.psd.conf` file was destroyed. I then started and stopped the process with systemctrl. I then checked the newly created `.psd.conf` file and saw that there was not a line of `BACKUP_LIMIT=1`. Also, no backup directories were deleted.

I then ran a `psd c` to clean, which deleted the backups, and explicitly set `USE_BACKUPS="yes"`, but when repeating the above steps still the `.psd.conf` file did not contain this line.

**Comment by graysky2** [comment]
This should now be corrected.
