### ISSUE TITLE
User service took >25s to startup causing blocking problems

### ISSUE THREAD

**Issue by N46AN** [graysky2/profile-sync-daemon#216]
Step to reproduce:

1. Enable the psd user service
2. Reboot
3. Login

Expected behaviour:
It should login normally

Actual behaviour:
It took exactly extra 25s to complete the first login, with the following error msg:
```pam_systemd(login:session): Failed to create session: Connection timed out```

After this, it's not possible to disable the psd user service because "Failed to get properties: Process org.freedesktop.systemd1 exited with status 1"

When attemping to preview psd status, it says "ERROR: Cannot find XDG_RUNTIME_DIR which should be set by systemd."

It seems that the initial startup is not working well with systemd. See: https://github.com/systemd/systemd/issues/2863

**Comment by graysky2** [comment]
Not sure what I can do; if `/run/user/xxxx` isn't created, there is no tmpfs onboard.  What happens if you disable the service, reboot, login and manually start it?  Guessing it's fine.

On my systems, psd just works.  No need for any manual starts.

**Comment by N46AN** [comment]
> What happens if you disable the service, reboot, login and manually start it? Guessing it's fine.
Yes, I am currently using this workaround.

As for workarounds, I thought about changing service type from "oneshot" to "simple", and use other means to detect whether service is active or inactive. But this seems ugly, and I'm not very familiar with systemd stuff, so not sure if this would work.

**Comment by aasril** [comment]
@graysky2 I'm also having this exact problem. Linux Mint 18.3 with psd v6.31 installed from ppa. Since I couldn't use `systemctl --user disable` command to disable psd on start-up I have to delete it manually from `~/.config/systemd/user/default.target.wants` directory.

Though with
```
$ grep tmpfs /proc/mounts
udev /dev devtmpfs rw,nosuid,relatime,size=2970252k,nr_inodes=742563,mode=755 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=600228k,mode=755 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
cgmfs /run/cgmanager/fs tmpfs rw,relatime,size=100k,mode=755 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=600228k,mode=700,uid=1000,gid=1000 0 0
```
I can see that I have /run/user/1000 mounted as tmpfs.

**Comment by aasril** [comment]
I see that in the psd service there is this line
`After=winbindd.service`
I looked it up and it's a samba-related service. I don't have samba installed. Can it be the problem?

**Comment by aasril** [comment]
I see that in the psd service there is this line
`After=winbindd.service`
I looked it up and it's a samba-related service. I don't have samba installed. Can it be the problem?

Edit1: It's not working by simply installing samba.
Edit2: Apparently to have winbindd I need to install `libpam-winbind libnss-winbind winbind`. But the service name is winbind not winbindd.

```
$ systemctl status winbind.service
● winbind.service - LSB: start Winbind daemon
   Loaded: loaded (/etc/init.d/winbind; bad; vendor preset: enabled)
   Active: active (running) since Sat 2019-04-13 10:34:35 WIB; 1min 42s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2277 ExecStart=/etc/init.d/winbind start (code=exited, status=0/SUCCESS)
    Tasks: 4
   Memory: 15.2M
      CPU: 285ms
   CGroup: /system.slice/winbind.service
           ├─4339 /usr/sbin/winbindd
           ├─4341 /usr/sbin/winbindd
           ├─4423 /usr/sbin/winbindd
           └─4430 /usr/sbin/winbindd
```

**Comment by graysky2** [comment]
@aasril - Can you install from source?  I have not been able to update my PPA for some time.  I should really delete it.

**Comment by aasril** [comment]
@graysky2 I removed ppa version and installed `psd` from source. It tells that it's v6.34 now.

I enabled the `psd.service` and the issue still occurred. I rebooted a couple of times to make sure. 

Please just mention me if you have something that you want me to try. I have an idea to comment `After=winbindd.service` but I hesitated to do that since I don't understand how this all work together and haven't looked into it more yet.

**Comment by graysky2** [comment]
@aasril - How are you using samba?  Go ahead and try that.

**Comment by aasril** [comment]
@graysky2 I'm not connected to a network where I can test this. But the service is running and adding an account works.

**Comment by graysky2** [comment]
Still an issue?

**Comment by aasril** [comment]
For me, sorry I can't tellI. I uninstalled psd since then.
