### ISSUE TITLE
Firefox profile detection fails if path contains whitespaces

### ISSUE THREAD

**Issue by muesli4** [graysky2/profile-sync-daemon#226]
The code assumes that profile paths do not contain whitespaces. There are 2 points where this fails:
* `common/browsers/firefox` will detect the segments as individual path due to use of `$(..)` while constructing `DIRArr`.
* The other place where this fails is `sed 's/ /\n/g'` at: https://github.com/graysky2/profile-sync-daemon/blob/d4ed380f9f3ed959879bbeaeb57bc4b6aab219e1/common/profile-sync-daemon.in#L381

My profile is called `m9fzdx84.Default User`. This could be related to https://github.com/graysky2/profile-sync-daemon/issues/205.

**Comment by timofonic** [comment]
@graysky2 Any news?
