### ISSUE TITLE
Remove mandatory modinfo dependency

### ISSUE THREAD

**Issue by azahi** [graysky2/profile-sync-daemon#232]
Some people are running module-less kernels without any userspace software such as `modinfo` or `kmod`.
It would be really nice if support for OverlayFS could be determined using some other method, for example, with `zcat /proc/config.gz | grep CONFIG_OVERLAY_FS=y`

**Comment by graysky2** [comment]
We could `zgrep -q 'CONFIG_OVERLAY_FS=y' /proc/config.gz` and then fallback to the modinfo method, but why does the check against `/proc/filesystems` fail in your case?

https://github.com/graysky2/profile-sync-daemon/blob/master/common/profile-sync-daemon.in#L145

**Comment by azahi** [comment]
I was running a module-less Gentoo on `gentoo-sources` with OverlayFS support compiled in back then IIRC and I'm sure that I pulled PSD from upstream directly. Unfortunately I don't have that machine now and I'm pretty sure that the error was fatal when I tried to run PSD. The error message was something like "modinfo is not found on your system" and I didn't see any mention of probing `/proc/filesystems`.

Not sure if I should close the issue or leave it be.

**Comment by graysky2** [comment]
Correct, the dep checks will error out if it's not on the system: https://github.com/graysky2/profile-sync-daemon/blob/master/common/profile-sync-daemon.in#L190

**Comment by graysky2** [comment]
I'm thinking closing is best since kmod is going to be present on most systems.

**Comment by eMPee584** [comment]
On debian systems, `modinfo` is in `/sbin/ `, so the current way requires symlinking kmod manually to `/usr/local/bin` f.e. to work, additionally to setuid /bin/kmod it seems to make `psd` command work.. Couldn't figure out a way to invoke kmod without the modinfo symlink.
Is there any situation where checking `/proc/filesystems` would not be enough?
