### ISSUE TITLE
Brave browser support

### ISSUE THREAD

**Issue by suiri** [graysky2/profile-sync-daemon#233]
Thanks for maintaining PSD, it is great tool for SSDs and generally speeding up browsing.

Would you please consider adding support for Brave browser? [brave.com](https://brave.com)

It is based on Chromium and seems to have same profile structure as Google Chrome located here
~/.config/BraveSoftware/Brave-Browser

Thanks.

**Comment by graysky2** [comment]
Since we have this modular support via dropins, I don't want to "officially" support more browsers.  Doing so means I tested them.

**Comment by AnwarShah** [comment]
@graysky2 What preventing you from officially list Brave where you've listed many browsers already, even Vivaldi-Snapshots.

**Comment by felipec** [comment]
> Since we have this modular support via dropins, I don't want to "officially" support more browsers. Doing so means I tested them.

Except there's no way for a user to configure the Brave browser, not until #271 is merged. `/usr/share/psd/browsers/` is not a user directory.
