### ISSUE TITLE
problems installing on fedora 28 with gnome 3

### ISSUE THREAD

**Issue by millerthegorilla** [graysky2/profile-sync-daemon#234]
Hi, I tried installing using the src from github, running make install from a wheel-group enabled account with no home directory.  I found myself stuck with the user unable to view the profiles, which /usr/bin/psd reported as belonging to root.  I uninstalled and then reinstalled having added my normal user to the wheel group, to enable sudo, so that I could then run sudo make install.
    systemctl --user start psd
then reported that systemctl could not find a psd.service file.  I located the file in /usr/lib/systemd/user/psd and reran the command with the fully qualified file path for the unit service file.
    systemctl --user start /usr/lib/systemd/user/psd
and the following was reported:
Failed to start usr-lib-systemd-user-psd.mount: Unit usr-lib-systemd-user-psd.mount not found.
psd p reports:
    psd p
    Profile-sync-daemon v6.33 on Fedora 28 (Workstation Edition)

     Systemd service is currently inactive.
     Systemd resync-timer is currently inactive.
     Overlayfs technology is currently inactive.

    Psd will manage the following per /home/xxxxx/.config/psd/psd.conf:

     browser/psname:  firefox/firefox
     owner/group id:  xxxxx/1000
     sync target:     /home/xxxxx/.mozilla/firefox/xxxxxx.default
     tmpfs dir:       /run/user/1000/xxxxx-firefox-xxxxxx.default
     profile size:    24M
     recovery dirs:   none

uname -a :
    4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by graysky2** [comment]
Are you still facing this?

**Comment by graysky2** [comment]
No response in 6+ mo.  Reopen if still facing.
