### ISSUE TITLE
`XDG_HOME_CONFIG` typo?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [graysky2/profile-sync-daemon#237]
https://github.com/graysky2/profile-sync-daemon/blob/9d2d7bb76b0d368b0e9e15bd3a32490908704dcb/common/psd.conf#L2

Is this a typo?  Shouldn't it be `XDG_CONFIG_HOME`?

**Comment by graysky2** [comment]
Yep, will fix thanks.
