### ISSUE TITLE
Vimb support

### ISSUE THREAD

**Issue by spiderbit** [graysky2/profile-sync-daemon#238]
Any plans on supporting vimb?

seems to be similar then luakit:

```
~ $ ls .cache/luakit/WebKitCache/
Version 13

~ $ ls .cache/vimb/WebKitCache/
Version 12
```

spontanious I think it's a better browser than luakit better config system, better hint system and better default fonts.

**Comment by graysky2** [comment]
See https://github.com/graysky2/profile-sync-daemon/issues/208
