### ISSUE TITLE
systemd requirement

### ISSUE THREAD

**Issue by Hypoon** [graysky2/profile-sync-daemon#239]
My full-system upgrade was completely disrupted when psd attempted to pull in systemd as a dependency. I came to the github page for psd and read your statement regarding removing support for alternative init systems in version 6. I now have four options:

1. Switch to systemd
2. Use an old version of psd
3. Abandon psd completely
4. Change your mind

I run Gentoo. I avoid systemd at all costs. I'm not interested in being convinced otherwise at this time.

Is there any chance you would reconsider adding support for OpenRC? Depending on the amount of work entailed, I may personally be willing to maintain OpenRC support. I noticed that the ebuild is also marked as needing a maintainer, and I might be willing to do that as well.

The old versions of psd were removed from Portage on February 23 after version 6.31 was marked stable on February 22, which explains why this came to my attention now.

**Comment by graysky2** [comment]
Sorry, but since my primary distro switched to systemd I have psd using it natively for simplicity.  I have no plans to divorce psd from systemd.
