### ISSUE TITLE
psd p shows overlayfs active without adding user at raspbian.

### ISSUE THREAD

**Issue by yutayu** [graysky2/profile-sync-daemon#242]
title.
Great job :)

**Comment by graysky2** [comment]
You haven't provided enough detail for me to reproduce or even understand what issue you're experiencing.

**Comment by yutayu** [comment]
From Readme
Note that if you're using overlayfs mode, your user needs to have sudo right to /usr/bin/psd-overlay-helper or else psd will refuse to run in overlayfs mode.

I didn't set sudo,but psd p shows overlayfs adcitve.
