### ISSUE TITLE
Permanent data lost on unexpected power loss

### ISSUE THREAD

**Issue by Azq2** [graysky2/profile-sync-daemon#244]
After any power loss i need manual restore chromium folder:
```
systemctl --user stop psd
cd ~/.config
rm -rf chromium
cp -pR chromium-backup-crashrecovery-20190723_115402 chromium
systemctl --user start psd
```

This a very terrible. 

In syslog i have:
```
Jul 23 11:54:01 localhost systemd[1354]: Started Timer for profile-sync-daemon - 1Hour.
Jul 23 11:54:02 localhost profile-sync-daemon[1391]: Ungraceful state detected for /home/user/.config/chromium so fixing
Jul 23 11:57:24 localhost profile-sync-daemon[1391]: mv: cannot move '/home/user/.config/chromium-back-ovfs' в '/home/user/.config/chromium': Directory not empty
Jul 23 11:57:25 localhost profile-sync-daemon[1391]: #033[01mchromium sync successful#033[00m
```

After few minutes of debug i found some problems. 
What's happening by step:

1. Run chromium and press hard reset button on PC. 
2. Poweron PC
3. `profile-sync-daemon` detects `Ungraceful state` by existance broken symlink ~/.config/chromium
4. `profile-sync-daemon` deletes symlink `~/.config/chromium`
5. `profile-sync-daemon` begin copying `~/.config/chromium-back` into `~/.config/chromium-crashrecovery-$NOW` for backup purposes. That takes a long time!!!
6. But user fast like
lightning and he launches Chromium after ~1 minutes from boot!!! On this moment №5 not finished!!!!! Chromium creates own `~/.config/chromium` with default config. 
7. After long time ago `profile-sync-daemon` has finished backup process. And tries move `~/.config/chromium-back-ovfs` to `~/.config/chromium`. But chrome already launched and `~/.config/chromium` already exists. We got error `Directory not empty`. :( 

Need some kind of locking mechanism for browser launch before crashrecovery copying not finished. May be link ~/.config/chromium to /dev/null, not sure.

And `USE_BACKUPS=no` wont fix this. A description of the alleged problem was written here earlier, but I was wrong.
Need more time for debug it later (why USE_BACKUPS=no wont fix this issue).

**Comment by graysky2** [comment]
OK... you're saying the cp in https://github.com/graysky2/profile-sync-daemon/blob/master/common/profile-sync-daemon.in#L283 takes a long time.  When it is running, a user launches the browser which reads/writes while the setup is still running.  Do I understand correctly?

**Comment by graysky2** [comment]
Should be fixed now.
