### ISSUE TITLE
Ungraceful state detected even though state is graceful using an encrypted homedir with mounting at login

### ISSUE THREAD

**Issue by Riamse** [graysky2/profile-sync-daemon#246]
I have a configuration that resembles https://wiki.archlinux.org/index.php/Dm-crypt/Mounting_at_login .` /home/` is mounted when I log in, and unmounted when I log out.

Problem is, every time I log in, `psd p` sees an ungraceful state, and makes a new crash recovery backup. I can log in, `systemctl --user stop psd`, log out, log back in, and it'll do it again.

I think it's probably a systemd problem or a pam problem and there's an issue with exactly when /home gets mounted and unmounted, but I have no idea how to debug that. (I'm fully willing to debug, to be clear.)

**Comment by Riamse** [comment]
Just kidding, I don't even have to log out. Simply saying `systemctl --user restart psd` and then `psd p` is sufficient to make a new backup (repeat these two commands and you can make identical backups galore). So it's not a mounting problem at all.

Exactly how is psd checking for ungraceful state and backup status? Whatever it's currently doing is not very robust and leads to the trigger-happy backing up phenomenon.

**Comment by graysky2** [comment]
> Exactly how is psd checking for ungraceful state and backup status? Whatever it's currently doing is not very robust and leads to the trigger-happy backing up phenomenon.

https://github.com/graysky2/profile-sync-daemon/blob/master/common/profile-sync-daemon.in#L235

I haven't used encryption in ages and I am unfamiliar with that setup.  If you are logged in, I assume that means your homedir is writable.

Please post your psd.conf

**Comment by graysky2** [comment]
No response in 6+ mo.  Reopen if still facing.
