### ISSUE TITLE
Snapped Firefox on Ubuntu 18.04 does not start

### ISSUE THREAD

**Issue by AlexanderAntimonov** [graysky2/profile-sync-daemon#247]
Firefox installed as a snap package on Ubuntu 18.04 does not start saying it is already running (but it is not). I figured out the cause of this is symlink to a profile folder in the tmpfs. If I use bound mount instead of symlink Firefox starts.

In psd.conf: BROWSERS="firefox-snap"

profile.default - is symlink to profile in tmpfs

cd ~/snap/firefox/common/.mozilla/firefox
mv profile.default profile.default.symlink
mkdir profile.default
sudo mount --bind /path/to/tmpfs/user-firefox-snap-profile.default profile.default 
start Firefox
exit Firefox
sudo umount profile.default
mv profile.default.symlink profile.default

[firefox-snap.txt](https://github.com/graysky2/profile-sync-daemon/files/3602040/firefox-snap.txt)

**Comment by graysky2** [comment]
Not sure what a snap package is...

**Comment by graysky2** [comment]
I haven't tested this version of firefox with psd and I don't understand how it is different from vanilla firefox so I would deem it as unsupported for now.

**Comment by pehlm** [comment]
Is it possible to get this supported in time Ubuntu makes [Firefox snap version the default in 21.10](https://www.omgubuntu.co.uk/2021/09/ubuntu-makes-firefox-snap-default)? Thanks!
