### ISSUE TITLE
To reduce tmpfs size , How about flushing files to disk per specific time if no accesses files.

### ISSUE THREAD

**Issue by yutayu** [graysky2/profile-sync-daemon#251]
I use 2 browser , sometimes it almost makes tmpfs full.
So I suggest if no acceses to files , flush and keep tmpfs's space.

**Comment by graysky2** [comment]
Hmmm... a bit out of scope since it would by definition destroy data.  Have you enabled overlayfs?

**Comment by yutayu** [comment]
>Have you enabled overlayfs?
Yes, I have , and I have enabled sudo for overlayfs.

I don't use 2 browser at once , then I closed 1 browser , I expected psd to flush profiles to backup.

**Comment by yutayu** [comment]
tmpfs            88M   59M   30M  67% /run/user/1000
overlaid         88M   59M   30M  67% /run/user/1000/pi-vivaldi
overlaid         88M   59M   30M  67% /run/user/1000/pi-google-chrome
overlaid         88M   59M   30M  67% /run/user/1000/pi-firefox-grdfarwg.default
overlaid         88M   59M   30M  67% /run/user/1000/pi-chromium

:P

**Comment by yutayu** [comment]
suggested function [flush timer].
I feel lack of prepared overlaidfs sometimes.
Then , I expected psd to flush no accessed files to disk.
It also reduces lack of ram.

**Comment by yutayu** [comment]
I imagine firefox limited size cache folder.
Firefox is flushing old cache files to shape limited size cache folder..

**Comment by graysky2** [comment]
I understand your problem, but deleting data is out of scope of my utility.

**Comment by yutayu** [comment]
agyaaaa lol
