### ISSUE TITLE
[feature request] let me sync an arbitrary directory

### ISSUE THREAD

**Issue by majcosta** [graysky2/profile-sync-daemon#263]
I wonder if there could be a psd.conf option to just sync a directory as if it were a browser profile, I've been using anything-sync-daemon but it just isn't being maintained, backups don't work, flaky stopping and starting the service, etc

tl;dr: just pretend ~/mydir is a browser profile :-)

thanks

**Comment by graysky2** [comment]
One of these days, I'll rebase the asd codebase with psd's but it's just low on the list of things to do.  psd has always been aimed at browsers and has checks to make sure they aren't running on stop, start etc. so it would be a chore to implement hat you're asking to have.
