### ISSUE TITLE
Support Brave browser

### ISSUE THREAD

**Issue by coxackie** [graysky2/profile-sync-daemon#264]
well; the issue title says it all    :)

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/issues/207
https://github.com/graysky2/profile-sync-daemon/issues/233
https://github.com/graysky2/profile-sync-daemon/pull/262
https://github.com/graysky2/profile-sync-daemon/pull/240
https://github.com/graysky2/profile-sync-daemon/pull/175

**Comment by brauliobo** [comment]
I get brave is unsupported and it isn't listed in the `Possible values` for `BROWSERS`

```
~ ❯❯❯ systemctl --user status psd
× psd.service - Profile-sync-daemon
     Loaded: loaded (/usr/lib/systemd/user/psd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-06-08 13:34:38 -03; 5s ago
       Docs: man:psd(1)
             man:profile-sync-daemon(1)
             https://wiki.archlinux.org/index.php/Profile-sync-daemon
    Process: 484750 ExecStart=/usr/bin/profile-sync-daemon startup (code=exited, status=1/FAILURE)
   Main PID: 484750 (code=exited, status=1/FAILURE)
        CPU: 34ms

jun 08 13:34:38 phoenix systemd[1418]: Starting Profile-sync-daemon...
jun 08 13:34:38 phoenix sudo[484764]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
jun 08 13:34:38 phoenix sudo[484764]:  braulio : PWD=/home/braulio ; USER=root ; COMMAND=/usr/bin/psd-overlay-helper
jun 08 13:34:38 phoenix sudo[484764]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
jun 08 13:34:38 phoenix sudo[484764]: pam_unix(sudo:session): session closed for user root
jun 08 13:34:38 phoenix profile-sync-daemon[484750]:  brave is not a supported browser. Check config file for typos: /home/braulio/.config/psd/psd.conf
jun 08 13:34:38 phoenix systemd[1418]: psd.service: Main process exited, code=exited, status=1/FAILURE
jun 08 13:34:38 phoenix systemd[1418]: psd.service: Failed with result 'exit-code'.
jun 08 13:34:38 phoenix systemd[1418]: Failed to start Profile-sync-daemon
```

**Comment by brauliobo** [comment]
it seems this project is unmaintained :cry: maybe @graysky2 you should add another active developer as a contributor

**Comment by graysky2** [comment]
It's maintained.  Why are you posting the same stuff to multiple closed issues?  I've made this pretty clear.

**Comment by brauliobo** [comment]
@graysky2 it really got me confused even after going to 5 tickets I had to find my own solution to make the brave configuration usable

**Comment by D3vil0p3r** [comment]
> @graysky2 it really got me confused even after going to 5 tickets I had to find my own solution to make the brave configuration usable

@brauliobo Can you write how you make configuration usable?

@graysky2 man, the "open source" philosophy should be inclusive, not exclusive. Despite there are a lot of users asking for Brave support, why don't you want to support it? There are supported "browsers" like `vivaldi-snapshot" "opera-beta" "google-chrome-unstable"... Supporting these (mostly for beta and unstable versions) and not Brave browser is like joking on users.

**Comment by Lumipyry** [comment]
Here is how to use Brave Browser wit psd:

Create a new file `brave` in `/usr/share/psd/browsers` that contains:

```
DIRArr[0]="$XDG_CONFIG_HOME/BraveSoftware/Brave-Browser"
PSNAME="brave"
```

**Comment by brauliobo** [comment]
guys, anything-sync-daemon is far superior than psd, I suggest migrating to it
