### ISSUE TITLE
psd wastes 100 % ram prepared by psd 

### ISSUE THREAD

**Issue by yutayu** [graysky2/profile-sync-daemon#268]
I need automatically sorting.
pi@raspberrypi:~/Documents $ apt info profile-sync-daemon
Package: profile-sync-daemon
Version: 6.31-1

**Comment by graysky2** [comment]
What?

**Comment by yutayu** [comment]
A profile can take up 100% of an overlay.

**Comment by graysky2** [comment]
I can't control the size of your profiles.  I don't see how this is an issue for upstream code to handle.

**Comment by yutayu** [comment]
Is it possible to delete a file with an old modification time by moving it to a backup?

**Comment by yutayu** [comment]
Or are infrequently updated files being replaced?

**Comment by graysky2** [comment]
I don't understand your questions.  psd isn't managing piece of your profile like that.

**Comment by yutayu** [comment]
Instead of consuming all the ram disks provided, I want to keep about 10% of them.

**Comment by yutayu** [comment]
pi@raspberrypi:~/Documents/profile-sync-daemon $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       916G  451G  419G  52% /
devtmpfs        433M     0  433M   0% /dev
tmpfs           438M  243M  196M  56% /dev/shm
tmpfs           438M   17M  421M   4% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           438M     0  438M   0% /sys/fs/cgroup
tmpfs           438M  1.6M  436M   1% /tmp
/dev/mmcblk0p1  253M   52M  202M  21% /boot
tmpfs            88M   40M   49M  45% /run/user/1000
overlaid         88M   40M   49M  45% /run/user/1000/pi-vivaldi
overlaid         88M   40M   49M  45% /run/user/1000/pi-epiphany
overlaid         88M   40M   49M  45% /run/user/1000/pi-google-chrome
overlaid         88M   40M   49M  45% /run/user/1000/pi-firefox-7dr1jmmf.default
overlaid         88M   40M   49M  45% /run/user/1000/pi-firefox-oa4fr69f.default-esr
overlaid         88M   40M   49M  45% /run/user/1000/pi-chromium

sometimes, USE% is 100%.

**Comment by graysky2** [comment]
You're using 5 different profiles on device with limited memory.  There is nothing psd can do to help you limit memory usage.  Recommend you scope it to manage one profile `$XDG_CONFIG_HOME/psd/psd.conf` and try to keep that profile's size under your limit. Also see Question 4 in `man 1 psd`

>Q4: I need more memory to accommodate my profile/profiles in /run/user/xxxx. How can I allocate more?
> 
> A4: The standard way of controlling the size of /run/user/ is the RuntimeDirectorySize directive in logind.conf (see the man page for logind.conf for more). By default, 10% of physical memory is used but one can increase it safely. Remember that tmpfs only consumes what is actually used; the number specified here is just a maximum allowed.

**Comment by yutayu** [comment]
ok thanks.
I use only firefox or vivaldi.
