### ISSUE TITLE
Support for Epiphany Webapps

### ISSUE THREAD

**Issue by b1-luettje** [graysky2/profile-sync-daemon#270]
Epiphany supports the creation of an arbitrary number of 'Web Apps', one description can be found [here](https://www.makeuseof.com/tag/epiphany-web-apps-integrate-web-desktop/).

They are stored under `$XDG_DATA_HOME/epiphany-<name>-<id>`, for example:

```shell
$ ls -ald .local/share/epiphany-*
drwxr-x--- 4 tluettje tluettje 4096  5. Aug 11:33 .local/share/epiphany-backup
drwxr-x--- 4 tluettje tluettje 4096  5. Aug 11:20 .local/share/epiphany-gitlab-9a9b09d909186a1ea088b925aea4172596fea7db
drwxr-x--- 4 tluettje tluettje 4096  3. Aug 15:39 .local/share/epiphany-jira-b25783a8e196a10e6c869d284bdfff09546e43d6
drwxr-x--- 4 tluettje tluettje 4096 29. Jul 09:11 .local/share/epiphany-syncthing-a008d57e7e550bb57893e55a9d5d7c84f3c93a78
```
The first entry only appears when #296 is aplied but it shows the necessity of differentiating between backups and the actual webapps. Would you support this feature? If so, i would try to draft a PR.

Thanks for your work!

**Comment by graysky2** [comment]
I am not interesting in officially supporting more browsers at this time.
