### ISSUE TITLE
[Bug] Sync before suspend does not release inhibit lock

### ISSUE THREAD

**Issue by smac89** [graysky2/profile-sync-daemon#275]
```
Linux ArcoB 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
Profile-sync-daemon v6.42
```

I've been noticing that my system takes a significant amount of time to sleep after I initiate the sleep process. After some research, I have come to the conclusion that it is being caused by `psd` not releasing the inhibit delay lock it acquires when the system is about to sleep.

Before I press the sleep button, you can see that `psd` registers some sort of inhibitor:

```
➜ systemd-inhibit --list
WHO                 UID  USER       PID    COMM            WHAT                                                                       WHY                                       MODE 
profile-sync-daemon 1000 chigozirim 629467 systemd-inhibit sleep                                                                      psd resync on suspend                     delay
```

When the system is about to sleep, we can see the following events:

```
Oct 06 14:29:09 ArcoB systemd-logind[934]: Suspend key pressed.
Oct 06 14:29:09 ArcoB root[638283]: SleepButton pressed
```

Next, we see `psd` start the syncing process:

```
Oct 06 14:29:09 ArcoB chigozirim[638287]: [psd-suspend-sync] Issueing suspend-sync request...
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: firefox resync successful
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: firefox resync successful
Oct 06 14:29:09 ArcoB profile-sync-daemon[638291]: vivaldi resync successful
```

At this point, `psd` has not released the lock, which leads the machine to wait until [`InhibitDelayMaxSec`](https://www.freedesktop.org/software/systemd/man/logind.conf.html#InhibitDelayMaxSec=) (5 seconds) expires, and then we see:

```
Oct 06 14:29:14 ArcoB systemd-logind[934]: Delay lock is active (UID 1000/chigozirim, PID 629467/systemd-inhibit) but inhibitor timeout is reached.
```

Only at this point does the system finally sleep.

---

P.S. It would be nice if there is some logging that goes on when the lock is released to the system.

**Comment by graysky2** [comment]
@glitsj16 - Any thoughts?  Very busy with work currently.

**Comment by smac89** [comment]
@graysky2 Just made a PR which should hopefully fix this.

**Comment by glitsj16** [comment]
@graysky2 I have been experiencing issues with suspend to RAM via systemd on my Arch Linux box for a while now. Haven't gotten around to debugging that, so I'm afraid I can't properly test the psd-suspend-sync feature currently.
