### ISSUE TITLE
Please add Microsoft Edge support

### ISSUE THREAD

**Issue by timofeika** [graysky2/profile-sync-daemon#279]
https://www.microsoftedgeinsider.com/en-us/download?platform=linux-deb

**Comment by graysky2** [comment]
Isn't Edge a fork of chrome?  You should be able to make a dropin modeled after chrome, if so: https://github.com/graysky2/profile-sync-daemon/blob/master/common/browsers/google-chrome

**Comment by Hazmi35** [comment]
> Isn't Edge a fork of chrome? You should be able to make a dropin modeled after chrome, if so: https://github.com/graysky2/profile-sync-daemon/blob/master/common/browsers/google-chrome

Adding them by default won't hurt right? I'm happy to create a PR for this
