### ISSUE TITLE
rm: cannot remove '/run/user/1000/.../index': Permission denied

### ISSUE THREAD

**Issue by Szunti** [graysky2/profile-sync-daemon#285]
The message was in the journal after `systemctl --user stop psd.service`
After that `systemctl --user start psd.service` failed with:
```
 profile-sync-daemon[2234]: Error in trying to mount /run/user/1000/... - this should not happen!
systemd[475]: psd-resync.service: Main process exited, code=exited, status=1/FAILURE
systemd[475]: psd-resync.service: Failed with result 'exit-code'.
```

The problem is trying to [rm -rf the workdir of overlayfs](https://github.com/graysky2/profile-sync-daemon/blob/80f7feeb04254865405a846a5403fc5651fd3368/common/profile-sync-daemon.in#L599), which only works
if the root-owned index directory is empty.

On my system archlinux, Linux 5.9.2, kernel config:
```
CONFIG_OVERLAY_FS=m
CONFIG_OVERLAY_FS_REDIRECT_DIR=y
# CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW is not set
CONFIG_OVERLAY_FS_INDEX=y
CONFIG_OVERLAY_FS_XINO_AUTO=y
CONFIG_OVERLAY_FS_METACOPY=y
```
index is not empty after deleting a file which is in the lower directory:
```
$mkdir lower upper work merged
$touch lower/f1
$sudo mount -t overlay overlaid -olowerdir=lower,upperdir=upper,workdir=work merged
$rm merged/f1
$sudo umount merged
$LANG=C rm -rf work
rm: cannot remove 'work/index': Permission denied
$sudo ls work/index
'#59a'
```

**Comment by graysky2** [comment]
Good catch.  Perhaps we can roll the `rm -rf "$TMP" "$UPPER" "$WORK"` into the umount function within `psd-overlay-helper` to avoid this.

**Comment by graysky2** [comment]
@Szunti - Good catch.  One thought is to roll the `rm -rf "$TMP" "$UPPER" "$WORK"` into the umount function within `psd-overlay-helper` to avoid this.

**Comment by graysky2** [comment]
Thank you for digging into this.
