### ISSUE TITLE
[Request] Support for librewolf

### ISSUE THREAD

**Issue by paapereira** [graysky2/profile-sync-daemon#289]
Hi there.
Any chance in supporting librewolf (a firefox fork)?

Thanks!

**Comment by graysky2** [comment]
You should be able to use the firefox profile editing it for this browser as a dropin.  See: https://github.com/graysky2/profile-sync-daemon/tree/master/common/browsers

I am not interesting in officially supporting more due to the overhead associated with testing/troubleshooting them.

**Comment by jeremiah-miller** [comment]
@paapereira did you end up creating a dropin for librewolf? Can you do `sudo cp /usr/share/psd/browsers/firefox /usr/share/psd/browsers/librewolf` and then in the librewolf file replace "/.mozilla/firefox" with "/.librewolf"? I tried that and it didn't work, do you know what I might be missing?

**Comment by paapereira** [comment]
Check out my 2 posts I made at my blog at the time: https://paapereira.xyz/tags/librewolf/.
The second one is a fix to the first one. Haven't change my setup since.
Arch Linux.

**Comment by jeremiah-miller** [comment]
I already had it set up the way you said, but it works now for whatever reason. Thanks!
