### ISSUE TITLE
news linux system / browsers - new default cache location

### ISSUE THREAD

**Issue by greglondon** [graysky2/profile-sync-daemon#290]
Hi,

Not sure if it's a newer system (Xubuntu 20.10) or new browsers default settings (Firefox 84, Chrome 87, Chromium 87), but cache location is different now.

PSD version 6.34-1

Default settings are:
Friefox - $HOME/.cache/mozilla/firefox/{profile name catalog}/
Chrome - $HOME/.cache/google-chrome/
Chromium - $HOME/.cache/chromium/

psd still creates links to old locations:
Friefox - $HOME/.mozilla/firefox/{profile name catalog}/
Chrome - $HOME/.config/google-chrome/
Chromium - $HOME/.config/chromium/

Could you please fix it in future releases?

Also any temporary solution to fix it in meantime myself? Which file to edit with default locations? And how to do that without loosing browsers data?

Probably files in /usr/share/psd/browsers/

I can see for Chrome and Chromium those files refer to XDG_CONFIG_HOME, but should be probably XDG_CACHE_HOME. Firefox refers to $HOME/.mozilla/firefox/, which should be changed to something else, but not sure.

Many thanks

**Comment by graysky2** [comment]
FYI - Your psd is out-of-date by >2 years.  Also, see the manpage re cache:
```
       Since  the  profile/profiles, browser cache*, etc. are relocated into tmpfs (RAM disk), the corresponding I/O associ‐
       ated with using the browser is also redirected from the physical disc to the RAM, thus reducing wear to the  physical
       disc and improving browser responsiveness.

       *Note  that  some browsers such as Chrome/Chromium, Firefox (since v21), Midori, and Rekonq actually keep their cache
       directories separate from their browser profile directory. It is not within the scope of profile-sync-daemon to  mod‐
       ify this behavior; users wishing to relocate this directory, may refer to the following url for several work-arounds:
       https://wiki.archlinux.org/index.php/Chromium_Tips_and_Tweaks#Cache_in_tmpfs
```
