### ISSUE TITLE
Version bump on PPAs/distro repos

### ISSUE THREAD

**Issue by Antonius-git** [graysky2/profile-sync-daemon#291]
Hi graysky, longtime user and fan of psd, it's a very handy program and I use it on every system I can.

I wanted to ask if you could ask or push for a version bump on some of the repositories linked on the main page (unsure of the procedure). 
To be honest, I didn't think psd was still being worked on (that it was pretty much complete and bug free) because e.g. Ubuntu 21.04 dev is still sporting the same version (**6.34**-1) from march 2019, but it's clear from the github commits that some bugs have been fixed (currently watching the overlayfs escalation issue #235  #286 ).

It means it's been a good while since any of the efforts put into psd here on github have been brought into the everyday. (To name a few: epiphany support fix; trigger resync on sleep; lots of documentation and syntax fixes; file permission work etc) - good stuff ripe for consumption!

Is there a planned big release upcoming (e.g. 6.50) before you'd like to have newer versions of the package dispersed? What's the procedure to ask for a recent version to be included into debian/ubuntu etc? 

Thanks for your time!

**Comment by graysky2** [comment]
Thanks for the kind words.  I am not sure what/how things get bumped for Ubuntu/Debian.  Try opening a bug report?
