### ISSUE TITLE
Which firefox folder to copy after insuccessful termination?

### ISSUE THREAD

**Issue by gruentee** [graysky2/profile-sync-daemon#293]
Hello, 

thanks for making profile-sync-daemon.

I had a few system freezes/power outages and afterwards wondered which folders to copy where in order to make psd work again. 
ArchWiki uses a Chromium example but is unclear about Firefox. Moreover it says

> Confirm that there is no symlink to the tmpfs browser profile directory. If there is, psd did not stop correctly for other reasons.

I always have this dangling symlink and deleted it in order to copy the `firefox-backup` folder to it's original location (after having stopped psd).
Upon restarting psd it fails. Only when manually executing `psd p`  afterwards it starts again.

So - what to do after unexpected shutdown or power outage when using Firefox?

**Comment by graysky2** [comment]
You shouldn't need to copy things over these days, the script should recover itself.  Post the output of `psd p`.  Also know that `psd p` does not do any recovery, it simply parses the config and shows you stats.

**Comment by gruentee** [comment]
Hi, thanks for your quick response. I don't have `psd p`'s output at hand atm. I'll have to reproduce the error to get it. It was something along the lines "firefox folder already exists, copying to new location …".
