### ISSUE TITLE
Compatibility with opendoas

### ISSUE THREAD

**Issue by ZaheenJ** [graysky2/profile-sync-daemon#296]
Right now, this is only compatible with sudo, but it isn't to hard to get it to work with opendoas. I just quickly fixed it by replacing sudo with doas in /usr/bin/psd and /usr/bin/psd-overlay-helper and getting rid of the -k option which doesn't exist for doas. There is a similar option -L but it would have to be executed separately as in executing the command with doas and then calling doas -L. I could imagine there being an option in psd.conf where you could choose to use doas or not and then just have both the files run doas instead of sudo as I described above but I do not have the skills to implement that.

**Comment by ZaheenJ** [comment]
It did not actually work as smoothly as I thought it would, at least after a reboot. I am now just using [this script](https://wiki.archlinux.org/index.php/Firefox/Profile_on_RAM#The_script) but will leave the issue open for other people.

**Comment by gbaranski** [comment]
same issue, why it is closed?

**Comment by graysky2** [comment]
I have no knowledge about freebsd ports nor time to port this over.
