### ISSUE TITLE
Please support ungoogled chromium

### ISSUE THREAD

**Issue by boniek83** [graysky2/profile-sync-daemon#303]
Profile is in /home/$USER/.config/ungoogled-chromium/

$ cat ungoogled-chromium 
```
DIRArr[0]="$XDG_CONFIG_HOME/$browser"
PSNAME="$browser"
````

**Comment by BachoSeven** [comment]
What build are you using? By default, UG keeps its profiles in `.config/chromium` as Chromium would.

**Comment by boniek83** [comment]
https://chromium.woolyss.com/
Marmaduke because it has widevine and h264 support.

**Comment by BachoSeven** [comment]
oh ok. Note that, in order to have widevine, you could also just follow this FAQ entry: 

- https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm

(and on Arch you have [chromium-widevine](https://aur.archlinux.org/packages/chromium-widevine) )

**Comment by boniek83** [comment]
Yeah, but why I should waste my time doing that when there is perfectly working Marmaduke build available? Even with that there is no h264 in official ungoogled-chromium which causes some sites to not work at all e.g. twitch.

**Comment by graysky2** [comment]
You can do this via dropin.  https://github.com/graysky2/profile-sync-daemon/pull/240
