### ISSUE TITLE
Support brave and ungoogled-chromium

### ISSUE THREAD

**Issue by MCWertGaming** [graysky2/profile-sync-daemon#307]
Hey,

I wanted to ask, if you could add support for the Brave and ungoogled-chromium browsers. Both are based on the official chromium browser, so adding them shouldn't be to complicated.

Thank you!

**Comment by jvillasante** [comment]
What is needed to support brave?

**Comment by paxe** [comment]
See issue #240 regarding brave, there is a brave profile in the repo under config/ that you can add to your setup. I'm using brave-browser-stable as the process name rather than just brave.

**Comment by graysky2** [comment]
You can do this via dropin.  https://github.com/graysky2/profile-sync-daemon/pull/240
