### ISSUE TITLE
support doas instead of sudo

### ISSUE THREAD

**Issue by kugland** [graysky2/profile-sync-daemon#322]
I’m using `doas` exclusively in my system. I have `/usr/bin/sudo` as a symlink to `/usr/bin/doas`, which works most of the time. However, profile-sync-daemon fails to use overlayfs because it runs sudo with the parameter `-k`, which is unsupported by `doas`.

Apart from that, it should work. I have this line in my `doas.conf`:

`permit nopass <USERNAME> as root cmd /usr/bin/psd-overlay-helper`

**Comment by graysky2** [comment]
I do not have any resource to extend to another privilege escalation tool, since `sudo` is a standard, I use it.

**Comment by kugland** [comment]
> I do not have any resource to extend to another privilege escalation tool, since `sudo` is a standard, I use it.

If I sent a pull request adding suport for OpenBSD `doas`, would you consider merging it?

**Comment by graysky2** [comment]
Depends on how deeply the code is modified.  If it is major, I will likely not want to do it.

**Comment by frap129** [comment]
@kugland I submitted a PR to add doas support, see https://github.com/graysky2/profile-sync-daemon/pull/323
