### ISSUE TITLE
New Debian/Ubuntu packages? (since PPA archive is now -very- outdated)

### ISSUE THREAD

**Issue by mjeveritt** [graysky2/profile-sync-daemon#330]
Hi,
It looks like you may have had a build system in place to build DEBs or RPMs for Debian/Ubuntu/Redhat/CentOS in the past - is there code that could be added to the main repo to make this compatible with the packaging systems for these distros, in addition to the source packages/build instructions for Arch/Gentoo/etc ?!
I'm pretty sure this would be a useful package to have available for the Ubuntu/Debian ecosystem once again, as the old Launchpad project page/PPA is now considerable out-of-date!
Cheers,
veremitz/Michael.

**Comment by bonelifer** [comment]
Perhaps, the OPENSUSE build system as they support building more than just OpenSUSE packages: https://build.opensuse.org/

**Comment by graysky2** [comment]
Yeah, I stopped building it years ago.  Not sure how to disable it.  Thinking anyone would recognize the age of it and not install, preferring from source.

**Comment by mjeveritt** [comment]
What I was gonna propose, is sorting out a CI/CD build system for you, if DevOps wasn't your thing, and you preferred doing the programming/etc .. :)

**Comment by graysky2** [comment]
I do not run these nor do I have the time to support debian/ubuntu packages.  Thanks for the offer.
