### ISSUE TITLE
ADD support for firefox ESR

### ISSUE THREAD

**Issue by allanlaal** [graysky2/profile-sync-daemon#334]
binary name: `firefox-esr `
profile location: `~/.mozilla/firefox-esr`

**Comment by allanlaal** [comment]
currently psd detect all profiles under `~/.mozilla/firefox`, but not under `~/.mozilla/firefox-esr`

**Comment by graysky2** [comment]
You can do this via dropin.  https://github.com/graysky2/profile-sync-daemon/pull/240
