### ISSUE TITLE
Librewolf fails to launch after 6.47-1

### ISSUE THREAD

**Issue by phoropter** [graysky2/profile-sync-daemon#337]
I'm on Arch and have been using psd in combo with firejail and librewolf successfully for a while now. However, since the last update LW will not launch. I get a GUI pop-up error of “Your Firefox profile cannot be loaded. It may be missing or inaccessible”. If I downgrade back to 6.45 and reboot everything launches without issue.

I did notice that after upgrading then running `psd p`, it tells my all my profiles have 777 permissions.

**Comment by graysky2** [comment]
Not sure about firejail and if it plays a role nor about librewolf.  If you stop psd, make sure if you're using overlayfs that it is not mounted `mount|grep overlaid` does the browser work as expected?  If not, look at where the browser profile is expected and see what's wrong with it.  For firefox that location is `~/.mozilla/firefox`

**Comment by glitsj16** [comment]
@phoropter profile-sync-daemon 6.47 has changed a path and your firejail profile(s) need adjusting to account for that. I merged a [fix](https://github.com/netblue30/firejail/commit/2cfe3ea9d09b440e4b389084cda9c230a17e23c0) in Firejail yesterday but that is in our git code. Probably your distro's package doesn't have that yet. So you can either make the implemented changes in .local files until they arrive on your distro or [build firejail from git](https://github.com/netblue30/firejail/wiki/Using-firejail-from-git).

Hope this helps!

**Comment by graysky2** [comment]
@glitsj16 - thanks sharing that.  I wasn't aware that my little project here is out there in other stuff :+1: 

The quickest path to having Arch Linux incorporate your chances into its firefail package is for you to simply bump the version to a new release.  A slower path is to open a ticket requesting a patch to be added.  I recommend the first.

**Comment by phoropter** [comment]
@glitsj16 thanks much for that! I applied the changes to a librewolf.local file and things are working. And sorry to waste your time with this issue @graysky2 since it was obviously something that had to be changed on my side with a firejail file.
