### ISSUE TITLE
grep: warning: stray \ before -

### ISSUE THREAD

**Issue by glitsj16** [graysky2/profile-sync-daemon#338]
Hi, with `6.47-1` I'm getting a `grep warning` when running `profile-sync-daemon`, regardless of what flag I use:

```
$ profile-sync-daemon --help
grep: warning: stray \ before a
Profile-sync-daemon v6.45
[...]
```

```
$ profile-sync-daemon preview
grep: warning: stray \ before a
Profile-sync-daemon v6.45
[...]
```

When I edit /usr/bin/profile-sync-daemon L130 from
`  if ! declare -p BROWSERS | grep -q 'declare -\a'; then`
to
`  if ! declare -p BROWSERS | grep -q 'declare -a'; then`
the warning goes away.

Not sure, but it might have to do with [grep](https://archlinux.org/packages/core/x86_64/grep/) now depending on `pcre2` instead of `pcre` (cfr. [this](https://github.com/archlinux/svntogit-packages/commit/d94cab7a6d8a867115fe0dbb2d0e1ebadf6ce8c7) change).

Perhaps this impacts #337 too, but I don't use Librewolf to confirm.

Also, as you can see in the above output, the version shown is still at `6.45`, even though the package is now at `6.47`. Just a cosmetic thing, but I thought you might want to be informed on it nonetheless.

**Comment by manfred3000** [comment]
> Perhaps this impacts #337 too, but I don't use Librewolf to confirm.
I'm` running `librewolf` with [this](https://aur.archlinux.org/packages/profile-sync-daemon-librewolf) without issues on Arch Linux, but then I don't use `overlayfs`...

**Comment by graysky2** [comment]
Thanks guys, fixed in last commit
