### ISSUE TITLE
Newer psd breaks Firejail sandbox compatibility when starting Firefox

### ISSUE THREAD

**Issue by domker** [graysky2/profile-sync-daemon#339]
Distribution: Arch Linux

**profile-sync-daemon version 6.45.1 tmpfs dir path:**
`/run/user/1000/user-firefox-XXXXXXXX.default`
Result:
Firefox run fine when firejail sandbox and psd enabled.

**profile-sync-daemon version 6.48.1 tmpfs dir path:**
`/run/user/1000/psd/user-firefox-XXXXXXXX.default`
Result:
Firefox cannot detect the profile directory and won't start (when firejail sandbox and psd enabled)

**Temporary fix:**
Adding new psd path to whitelist:
firejail --whitelist=/run/user/1000/psd firefox

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-sync-daemon/issues/337
