### ISSUE TITLE
update README - psd on Archlinux is on "extra" not "community"

### ISSUE THREAD

**Issue by m040601** [graysky2/profile-sync-daemon#363]
On the README,

```
Officially Packaged

    Arch: in the community 
...
```

"community" is gone, link should be https://archlinux.org/packages/extra/any/profile-sync-daemon/

**Comment by graysky2** [comment]
Thanks, fixed in https://github.com/graysky2/profile-sync-daemon/commit/4307a5575f613a441dece17d0fd5360445cdf96b
