### ISSUE TITLE
Firefox Flatpak

### ISSUE THREAD

**Issue by jvillasante** [graysky2/profile-sync-daemon#367]
On Debian, with Firefox Flatpak how I can run this?

Should I set some permissions with Flatseal or just create a new config in `/usr/share/psd/browsers` that points to `~/.var/app/org.mozilla.firefox/.mozilla/firefox`?

I have tried both methods with no luck so far :(

**Comment by graysky2** [comment]
I am not familiar with that one.  The dropin is pretty straightforward to make once you know the location of your browser profile.  Study a few of them that are provided to see.
