### ISSUE TITLE
Feature request: Zen Browser support

### ISSUE THREAD

**Issue by bkuri** [graysky2/profile-sync-daemon#378]
Should be pretty straightforward since it's firefox-based:

- GitHub: https://github.com/zen-browser/desktop
- Homepage: https://zen-browser.app/

Thanks in advance!

**Comment by bkuri** [comment]
I made an AUR package to implement this here: https://aur.archlinux.org/packages/profile-sync-daemon-zen

FYI the `zen-browser` profile is placed in `/usr/share/psd/browsers` and looks like this:

```
if [[ -d "$HOME"/.zen ]]; then
    index=0
    PSNAME="zen-browser"
    while read -r profileItem; do
        if [[ $(echo "$profileItem" | cut -c1) = "/" ]]; then
            # path is not relative
            DIRArr[$index]="$profileItem"
        else
            # we need to append the default path to give a
            # fully qualified path
            DIRArr[$index]="$HOME/.zen/$profileItem"
        fi
        (( index=index+1 ))
    done < <(grep '[Pp]'ath= "$HOME"/.zen/profiles.ini | sed 's/[Pp]ath=//')
fi

check_suffix=1
```

**Comment by bkuri** [comment]
@itsHanibee good to know. I think I did this because I couldn't find Zen Browser in the README.

Thanks!

**Comment by itsHanibee** [comment]
> @itsHanibee good to know. I think I did this because I couldn't find Zen Browser in the README.
> 
> Thanks!

Have a point here, adding browsers available via contrib/ needs to be documented somewhere.

README or the Arch Wiki would work.

@graysky2 thoughts?

**Comment by ch4og** [comment]
Created PR https://github.com/graysky2/profile-sync-daemon/pull/380 that adds Zen Browser to README

**Comment by itsHanibee** [comment]
> Created PR #380 that adds Zen Browser to README

Nah, gotta be more specific I feel like. Community supported programs aren't gonna work ootb, people are gonna read that Zen is supported and will just use psd like normal and leave reports that it doesn't report properly.

More info is needed, maybe a section informing that there's "semi-official" support for certain browser and the steps to get them set up properly.

Another thing is that if we are adding Zen to the README, it's ideal to add all the other community browsers too just for completion's sake.
