### ISSUE TITLE
why psd not manage .cache?

### ISSUE THREAD

**Issue by nefelim4ag** [graysky2/profile-sync-daemon#63]
I think all browser content must be on ram, may be i mistake?
google-chrome writes and uses and uses ~/.cache/google-chrome

**Comment by grossws** [comment]
FTR, on distros with `systemd` it also can be achieved with unit `/etc/systemd/system/home-<username>-.cache.mount`:
```ini
[Unit]
Description=user cache dir
ConditionPathIsSymbolicLink=!/home/gross/.cache
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target
After=home.mount

[Mount]
What=tmpfs
Where=/home/gross/.cache
Type=tmpfs
Options=mode=0755,strictatime,nosuid,nodev,uid=gross,gid=gross

[Install]
WantedBy=local-fs.target
```

Of course, `gross` should be changed to your *username* (`gid` should exists), unit filename *must be changed* also. Written in assumption that `/home` is on separate partition thus `home.mount` used in `After` clause.

Then use `systemctl daemon-reload && systemctl enable home-<username>-.cache.mount`. Log out from DE/WM, clean `~/.cache` and check that `systemctl start home-<username>-.cache.mount` succeeds before reboot.

**Comment by parkerlreed** [comment]
At that point isn't .cache going to be wiped? I would assume a browser cache is something you may want to keep between reboots.

**Comment by graysky2** [comment]
I've scoped this outside of what I want to do with psd.  For reference, my ~/.cache has been mounted to tmpfs for a long time now and I have no ill effects.

**Comment by parkerlreed** [comment]
@graysky2 Ahh cool. Good to know. Thanks a ton for all the work put into this project!

**Comment by graysky2** [comment]
you're welcome, rock on

**Comment by grossws** [comment]
I'll also suggest to limit `tmpfs` size (by default it can are half of your RAM for `.cache`). If you're using `systemd` unit like I posted above, add `size=400M` (or any size you like) to `Options` directive. I found 400M more than enough for me, it usually keeps under 200M.

**Comment by remort** [comment]
Creating a copy of `/usr/share/psd/browsers/google-chrome`, f.e. `/usr/share/psd/browsers/firefox-cache`
Editing it as follows:
```
DIRArr[0]="/home/remort/.cache/mozilla/firefox"
PSNAME="firefox-cache"
```
Adding `firefox-cache` to `/home/remort/.config/psd/.psd.conf` as following:
`BROWSERS="firefox firefox-cache"`

Then closing firefox and restarting systemd psd service made the trick for me.

**Comment by yutayu** [comment]
How about using anyghin-sync-daemon?





Le jeudi 12 novembre 2020 à 04:58:05 UTC+9, remort <notifications@github.com> a écrit : 







Creating a copy of /usr/share/psd/browsers/google-chrome, f.e. /usr/share/psd/browsers/firefox-cache
Editing it as follows:
DIRArr[0]="/home/remort/.cache/mozilla/firefox"
PSNAME="firefox-cache"

Adding firefox-cache to /home/remort/.config/psd/.psd.conf as following:
BROWSERS="firefox firefox-cache"

Then closing firefox and restarting systemd psd service made the trick for me.

**Comment by parkerlreed** [comment]
Anything works as well but PSD is already running for me. Easier to let one daemon handle everything.

**Comment by yutayu** [comment]
If you think so , Asd can sync profile .
Ask asd all :)


Le vendredi 13 novembre 2020 à 02:00:37 UTC+9, parkerlreed <notifications@github.com> a écrit : 







Anything works as well but PSD is already running for me. Easier to let one daemon handle everything.

**Comment by remort** [comment]
Same story. PSD is already in use. SystemD units approach shown above is a killer too by the way. Maybe next time.

**Comment by yutayu** [comment]
I mean that how about stopping psd and  use asd for profile and all sync.




Le vendredi 13 novembre 2020 à 02:09:46 UTC+9, remort <notifications@github.com> a écrit : 







Same story. PSD is already in use. SystemD units approach shown above is a killer too by the way. Maybe next time.
