### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by jyc** [graysky2/profile-sync-daemon#76]
profile-sync-daemon is a very useful program, so thanks for writing it! Unfortunately, it seems to take a very long time to start on my Archlinux install. This is strange, as I am running on an SSD and `psd p` shows that I am sinking only around 200MB.

Here is a snippet of `systemd-analyze blame`:

```
[jonathan@jc-desk-arch ~]$ systemd-analyze blame
         12.477s psd.service
          1.187s NetworkManager.service
           213ms psd-resync.service
            93ms polkit.service
            92ms colord.service
            76ms systemd-logind.service
```

Here is the output of `psd p`:

```
[jonathan@jc-t430-arch ~]$ psd p
Profile-sync-daemon v5.47 on Arch Linux.

 Systemd service is currently active.
 Systemd resync service is currently active.

Psd will manage the following per /run/psd.conf settings:

 browser/psname:  chromium/chromium
 owner/group id:  jonathan/1000
 sync target:     /home/jonathan/.config/chromium
 tmpfs dir:       /tmp/jonathan-chromium
 profile size:    115M

 browser/psname:  firefox/firefox
 owner/group id:  jonathan/1000
 sync target:     /home/jonathan/.mozilla/firefox/ves25cl5.default
 tmpfs dir:       /tmp/jonathan-firefox-ves25cl5.default
 profile size:    53M

 browser/psname:  midori/midori
 owner/group id:  jonathan/1000
 sync target:     /home/jonathan/.config/midori
 tmpfs dir:       /tmp/jonathan-midori
 profile size:    1.3M
```

Thanks.

**Comment by dareni** [comment]
Without specifying BROWSERS it is slower so set eg:
`BROWSERS="firefox google-chrome"`

With BROWSERS="":
`daren@noddy:~/.config/psd$ time psd sync
firefox sync successful
google-chrome sync successful

real    0m7.152s
user    0m2.840s
sys     0m3.832s

daren@noddy:~$ systemd-analyze --user blame
         28.843s psd-resync.service
           156ms gvfs-daemon.service
            14ms psd.service
             8ms dbus.socket
`
With BROWSERS="firefox google-chrome":
`daren@noddy:~/.config/psd$ time psd sync
firefox resync successful
google-chrome resync successful

real    0m0.222s
user    0m0.068s
sys     0m0.056s

daren@noddy:~$ systemd-analyze --user blame
          2.749s psd-resync.service
           145ms gvfs-daemon.service
            12ms psd.service
            10ms dbus.socket
`
